// build-curated.js — يبني nabda-products.json من منتجات منسّقة يدوياً (بيانات مجلوبة مسبقاً)
// لا يجلب من الشبكة — تحويل صرف عبر mapper.
const fs = require('fs');
const cfg = require('./config');
const { toNabda } = require('./lib/mapper');

const YC = 'https://cdn.youcan.shop/stores/d1d928d672df45484133d940b08e6197/products/';
const yc = (...names) => names.map((n) => YC + n);

// raw: {name, price(sale), oldPrice, images[], description, url, store, category(override)}
const raw = [
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/doppler-foetal',
    name: 'Doppler Fœtal — جهاز مراقبة دقات قلب الجنين',
    price: '3500', oldPrice: '4400',
    category: 'أجهزة طبية',
    description: 'لا تخسري فرصة أن تكوني أقرب إلى قلب جنينك من أي وقت مضى ❤️\nجهاز دوبلر منزلي يتيح لكِ سماع نبضات قلب جنينكِ بوضوح وأمان، لحظات لا تُنسى بين الأم وطفلها.',
    images: yc('UOvOcjJoIunrm8ajUmEqGbrCza3RYQJ0T6iTwW4i.png','Zo9hlAX35Hf0EFrSoE5wdKL4NqRvCLj06f0hIYvI.png','Y0rUxLApOc2xvhUvrjCk0J6m8px5fjAkGjaJvA3m.png','dQ3dRRY8nGXPdyDEMCCT974QG1CcPWQpqwCTS5Qr.png'),
  },
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/ceinturedegrossesse',
    name: 'حزام دعم الحوامل — الأصلي من Sibote',
    price: '1800', oldPrice: '2900',
    category: 'عناية بالحامل',
    description: 'راحتك وأمان طفلك قبل كل شيء!\nحزام الأمومة الأصلي من Sibote يرفع عنك ثقل البطن ويخلصك من آلام الظهر، يخفف ترهلات البطن بعد الولادة، ويتأقلم مع نمو طفلك طوال التسعة أشهر. مناسب داخل المنزل وخارجه ولا يظهر تحت الملابس.',
    images: yc('y6khV0WW2sSIACWdjAXsXelu2UH7CQRdLbLBIdky.png','DEHtPlpR1JTz2ck831TTjnTkFigp8Ns16kORicSg.png','J8298dFwh4S8eolAxUwd66hXDYCqBbdROaOilc8S.jpg','pVGEOBY9BGKC4rqduh88D6iEN2San0orGop3LYJr.png'),
  },
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/bas-therapeutiquecompression',
    name: 'جوارب الضغط الطبية للحوامل — Bas de Compression',
    price: '1900', oldPrice: '',
    category: 'عناية بالحامل',
    description: 'جوارب علاجية بالضغط المتدرج مخصصة لتخفيف الدوالي وانتفاخ القدمين عند الحوامل. تحفّز الدورة الدموية وتمنع احتباس السوائل، فتقلّ من التورم والشعور بالثقل في الساقين. مناسبة أثناء الحمل وبعد الولادة.',
    images: yc('geiYaArMckBK5wHZjEuWgOyWyiKFoeAr2mOyBrtI.jpg','9iCE7F0Cov5Yr0zNX3OSOsTMo2VsRhfeqSOgj6rc.jpg','kGVtL6HtGk24hQVOcsxtMWHLLHTcAaMhKap1O7Oz.jpg'),
  },
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/ceinture-post-accouchemen',
    name: 'مشد النفاس الثلاثي — الأصلي من Sibote',
    price: '2500', oldPrice: '3500',
    category: 'راحة الأم',
    description: 'مشد النفاس الثلاثي — الحل المثالي لاستعادة القوام الطبيعي بعد الولادة. يدعم ويشدّ البطن والخصر والحوض بشكل متزن، يقلل التمدد الناتج عن الحمل ويقوّي عضلات الظهر. ينصح به الأطباء.',
    images: yc('tZt3uygmJ53hQBbkdoPfoQ77IkaIImuDERMKN9tE.jpg','inLoIpHj8WvF2lLsI8Wosfb8DTD3NTJpiYcyzwAi.jpg','pQAUwxN4jgxzj3ZIp2xmP6CwsME3NdVm8yYACfJS.jpg','qJ5hlPv6oYzcnROfnwfJ5p9pcUBXjFB2eFDAODKg.jpg'),
  },
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/mymibellywing',
    name: 'رقع تنحيف البطن بعد الولادة — MYMI Belly Wing',
    price: '1550', oldPrice: '1900',
    category: 'راحة الأم',
    description: 'رقع MYMI Belly Wing لشدّ البطن بعد الولادة — ابتكار كوري للعناية بجمال الأم واستعادة الثقة بالنفس. مثالية ضمن روتين ما بعد الولادة.',
    images: yc('DI1ZNDt5w9YvcYK9NZeoNjtfcZypoz3BGsLOhWK1.png','cg5OzF9vHEAjhm61GYAxLrK1tMLW9IJForrdP3uF.png'),
  },
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/kbaa-alasthmam-latfal',
    name: 'قبعة الاستحمام للأطفال',
    price: '1990', oldPrice: '2500',
    category: 'لوازم الرضيع',
    description: 'قبعة استحمام مصنوعة من مادة طرية آمنة على البشرة، تحمي عيني طفلك من الماء والصابون أثناء الحمام. تصميم عملي ومريح مثالي للأطفال الصغار.',
    images: yc('IDdepYajuOznyJwpSYKDcP7D6ECBkrB4yRxk3lJS.jpg','s0gENl7fP2xrQCmhkcOh3UVrz9f77ssXSloT4rmi.jpg','vUO0sd2MU33TzqZmVftHPxQylPKUWc0Dj8dP7k4A.jpg'),
  },
  {
    store: 'Rasmin', url: 'https://rasmin.store/products/maternitypacks',
    name: 'باقة الأمومة — Pack de Maternité',
    price: '4990', oldPrice: '7800',
    category: 'حقيبة الولادة',
    description: 'باقة الأمومة المتكاملة من بداية الحمل حتى النفاس، بسعر خيالي. كل ما تحتاجه الأم في مرحلة الحمل وما بعد الولادة في باقة واحدة.',
    images: yc('nXwSWHfmxrNtAlA7VFMrIEbncO2ys4emghLomYxm.png','YOUwMQ6VUbP4jwtwskAAzGlyCFUbhh7QQ4MMBSwr.png'),
  },
  {
    store: 'Lactalove', url: 'https://lactalove.store/',
    name: 'Lactalove — شفاط الحليب اللاسلكي الذكي',
    price: '7800', oldPrice: '9500',
    category: 'الرضاعة والتغذية',
    description: 'شفاط حليب لاسلكي بالكامل، هادئ (أقل من 45 ديسيبل)، بـ 3 وضعيات (مساج • شفط عميق • تحفيز) و12 مستوى سرعة. بطارية تدوم حتى 6 استعمالات بشحنة واحدة، مع قمع إضافي للحلمة الصغيرة. حرية الحركة والراحة لكل أم مرضعة.',
    images: [
      'https://lactalove.store/wp-content/uploads/2025/10/495322976_122113552796839042_5611614320457913418_n-copy.webp',
      'https://lactalove.store/wp-content/uploads/2025/10/snapsave-app_3651111560001180853.jpg',
    ],
  },
  {
    store: 'Houloul', url: 'https://houloul-herbalance-dz.net/creemat-houloul55',
    name: 'كريمة طبيعية للبشرة — إزالة البقع البنية',
    price: '2300', oldPrice: '',
    category: 'عناية بالحامل',
    description: 'كريمة طبيعية للعناية بالبشرة وإزالة البقع البنية والتصبغات، مناسبة لبشرة الحامل والأم. تركيبة طبيعية آمنة للعناية اليومية.',
    images: ['https://houloul-herbalance-dz.net/user/home/images/product/product-creemat.png'],
  },
  {
    store: 'Houloul', url: 'https://houloul-herbalance-dz.net/anti-varice16',
    name: 'زيت طبيعي لعلاج الدوالي',
    price: '2900', oldPrice: '',
    category: 'عناية بالحامل',
    description: 'زيت طبيعي للتخلص من الدوالي وتحسين مظهر الأوردة — دعم للحوامل اللواتي يعانين من الدوالي وانتفاخ الساقين. العبوة: علبتان.',
    images: ['https://houloul-herbalance-dz.net/user/home/images/product/product-33.png'],
  },
  {
    store: 'Filaman', url: 'https://filaman-2.myshopify.com/products/%d8%a8%d8%a7%d9%82%d8%a9-%d8%b1%d8%a7%d8%ad%d8%a9-%d8%a7%d9%84%d8%a7%d8%b7%d9%81%d8%a7%d9%84',
    name: 'باقة راحة الأطفال',
    price: '2950', oldPrice: '3650',
    category: 'لوازم الرضيع',
    description: 'باقة راحة متكاملة للأطفال الصغار — مجموعة عملية تجمع أساسيات العناية والراحة للرضيع في حزمة واحدة بسعر مميز.',
    images: [
      'https://cdn.shopify.com/s/files/1/0834/5141/2705/files/Design_sans_titre_6.png?v=1780771807',
      'https://cdn.shopify.com/s/files/1/0834/5141/2705/files/1350577042_max_1.webp?v=1780771819',
      'https://cdn.shopify.com/s/files/1/0834/5141/2705/files/WhatsApp-Image-2022-06-13-at-10.25.34-AM-1.jpg?v=1780771823',
      'https://cdn.shopify.com/s/files/1/0834/5141/2705/files/6042084224950979153_120_222866f9-08b8-4e18-8f03-ed39b9e317a9_1.webp?v=1780771827',
      'https://cdn.shopify.com/s/files/1/0834/5141/2705/files/WhatsApp-Image-2022-06-13-at-10.25.34-AM-1_1.jpg?v=1780771830',
    ],
  },
  {
    store: 'Pb9d17', url: 'https://pb9d17-1q.myshopify.com/products/%D9%85%D8%B6%D8%AE%D8%A9-%D8%A7%D9%84%D8%AD%D9%84%D9%8A%D8%A8-%D8%A7%D9%84%D9%83%D9%87%D8%B1%D8%A8%D8%A7%D8%A6%D9%8A%D8%A9-%D8%A7%D9%84%D8%B0%D9%83%D9%8A%D8%A9-%D8%B1%D8%A7%D8%AD%D8%A9-%D9%88%D8%A3%D9%85%D8%A7%D9%86-%D9%84%D9%83%D9%84-%D8%A3%D9%85',
    name: 'مضخة الحليب الكهربائية الذكية — راحة وأمان لكل أم',
    price: '5500', oldPrice: '',
    category: 'الرضاعة والتغذية',
    description: 'مضخة حليب كهربائية ذكية توفر شفطاً لطيفاً وفعّالاً بمستويات قابلة للتحكم، لتجربة رضاعة مريحة وآمنة لكل أم. تصميم عملي وهادئ يمنحكِ الراحة والحرية.',
    images: [
      'https://cdn.shopify.com/s/files/1/0658/6748/1224/files/S45f4465df16344efa561d1c8aa444a27X.png?v=1772275051',
    ],
  },
  {
    store: 'ALGO (myecomsite)', url: 'https://deatheat.myecomsite.net/-27CaezCO',
    name: 'باك 6 قطع للتغذية الفاخر للرضّع من ALGO',
    price: '6900', oldPrice: '',
    category: 'الرضاعة والتغذية',
    description: 'طقم تغذية فاخر للرضّع من ALGO مكوّن من 6 قطع — أدوات آمنة وعملية لإطعام طفلك بجودة عالية. أكثر من 2000 زبون راضٍ. الدفع عند الاستلام.',
    images: [
      'https://assets.lightfunnels.com/account-43411/images_library/d4d1e1bd-d0c5-4e90-a465-cbc24e41279e.UY2gKnek9S15rxss_e50l.webp',
      'https://assets.lightfunnels.com/account-43411/images_library/6a5eddcb-a1e8-4d0a-8fce-9095b9fe046d.U-2KFzvXcJ3kAP2DACQra.webp',
      'https://assets.lightfunnels.com/account-43411/images_library/726c2736-c4a7-4e41-b1a4-971b67f2d889.-S5WN8LEQzFYLBmzV16mT.webp',
      'https://assets.lightfunnels.com/account-43411/images_library/4fc9e9c8-0a45-434f-9b7d-434ee18ca5a4.Zp0ElfVKuT53EBoGiOMwA.webp',
      'https://assets.lightfunnels.com/account-43411/images_library/8d0c4578-43bd-4afa-9ae2-9a44e25d57d8._erCneEwIVJclbPzRfSqp.webp',
      'https://assets.lightfunnels.com/account-43411/images_library/2a2c3c35-4080-42e4-bd39-230ed9d450d2.I_r6iUUhOB4C76aoQY4bC.webp',
    ],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'بساط ألعاب مائي تفاعلي للأطفال',
    price: '1400', oldPrice: '4900',
    category: 'ألعاب وتحفيز',
    description: 'بساط ألعاب مائي يحفّز حواس الطفل ويسلّيه بأمان أثناء اللعب على البطن.',
    images: ['https://cloud.flexdz.com/serve/file/cUN_ZSEJj__oUTtsyeutH-1776768049059.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'بساط الموسيقى التفاعلي للأطفال',
    price: '4500', oldPrice: '4700',
    category: 'ألعاب وتحفيز',
    description: 'بساط موسيقي تفاعلي يشجّع الطفل على الحركة والاكتشاف مع أصوات وأضواء محفّزة.',
    images: ['https://cloud.flexdz.com/serve/file/dnusgdU1Id5Kq6XR37nD2-1782145663792.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'كرسي هزّاز للأطفال',
    price: '4500', oldPrice: '5800',
    category: 'لوازم الرضيع',
    description: 'كرسي هزّاز مريح يهدّئ الرضيع ويساعده على الاسترخاء والنوم.',
    images: ['https://cloud.flexdz.com/serve/file/kwPlwUUs1bbMQ6Njm0UC8-1784227114628.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'كرسي هزّاز للأطفال — تصميم قطة',
    price: '4900', oldPrice: '6900',
    category: 'لوازم الرضيع',
    description: 'كرسي هزّاز بتصميم قطة لطيف، مريح وآمن لتهدئة الرضيع.',
    images: ['https://cloud.flexdz.com/serve/file/Y0F44_TV1XGOa1xSt1GLw-1777394352098.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'أرجوحة أطفال مع كرسي',
    price: '2500', oldPrice: '4000',
    category: 'لوازم الرضيع',
    description: 'أرجوحة أطفال بكرسي داعم توفّر راحة وأماناً للرضيع أثناء اللعب والراحة.',
    images: ['https://cloud.flexdz.com/serve/file/F80D5V8zzd8zCqrRdGZBr-1777390809037.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'مشاية أطفال مستوردة بالألعاب والموسيقى',
    price: '4300', oldPrice: '5900',
    category: 'لوازم الرضيع',
    description: 'مشاية أطفال مستوردة مزوّدة بألعاب وموسيقى لتحفيز الطفل ودعم خطواته الأولى.',
    images: ['https://cloud.flexdz.com/serve/file/PKMyQe59cB0jna4b4CMtB-1783880020771.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'مشاية أطفال مستوردة بعجلات',
    price: '3999', oldPrice: '6000',
    category: 'لوازم الرضيع',
    description: 'مشاية أطفال مستوردة بعجلات انسيابية تساعد الطفل على التنقّل بأمان.',
    images: ['https://cloud.flexdz.com/serve/file/mcnGhjp9oDtrts28ECeSB-1777552476844.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'مشاية أطفال مستوردة بدمية',
    price: '4700', oldPrice: '6000',
    category: 'لوازم الرضيع',
    description: 'مشاية أطفال مستوردة مع دمية تفاعلية تسلّي الطفل وتشجّعه على الحركة.',
    images: ['https://cloud.flexdz.com/serve/file/viv2uzkMBDGX68cef5NBD-1777550501724.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'مشاية أطفال محلية',
    price: '3300', oldPrice: '4000',
    category: 'لوازم الرضيع',
    description: 'مشاية أطفال محلية الصنع عملية وآمنة لدعم خطوات طفلك الأولى.',
    images: ['https://cloud.flexdz.com/serve/file/0bS8dDD3fB0ZiJl67ERTb-1777482986913.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'كرسي الأكل للأطفال',
    price: '5200', oldPrice: '7900',
    category: 'لوازم الرضيع',
    description: 'كرسي أكل عملي وآمن للأطفال، قابل للتعديل ليواكب نمو طفلك أثناء وجبات الطعام.',
    images: ['https://cloud.flexdz.com/serve/file/TtmCzHGAhSEc-C3zbL-X7-1783554962728.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'وسادة الجلوس الداعمة للأطفال',
    price: '2300', oldPrice: '3300',
    category: 'لوازم الرضيع',
    description: 'وسادة داعمة تساعد الرضيع على تعلّم الجلوس بثبات وأمان.',
    images: ['https://cloud.flexdz.com/serve/file/lAkILopeMcn3N3io2IGQW-1782398900082.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'مقعد أطفال على شكل سيارة — وردي',
    price: '2500', oldPrice: '4500',
    category: 'لوازم الرضيع',
    description: 'مقعد أطفال مريح بتصميم سيارة فاخرة يدعم جلوس الطفل بشكل مريح وممتع.',
    images: ['https://cloud.flexdz.com/serve/file/Qw9dC3FbmL_tb2FQkB0H6-1778500265164.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'كرسي سيارة للأطفال (عدة ألوان)',
    price: '6500', oldPrice: '8000',
    category: 'سفر وتنقل',
    description: 'كرسي سيارة آمن للأطفال متوفّر بعدة ألوان، يوفّر حماية وراحة أثناء التنقّل.',
    images: ['https://cloud.flexdz.com/serve/file/utVkmRRpA0w0PjjDWCemU-1775337204712.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'سرير أطفال مع بساط مائي',
    price: '4500', oldPrice: '6000',
    category: 'لوازم الرضيع',
    description: 'سرير أطفال عملي مع بساط مائي للعب والراحة، مثالي للرضّع.',
    images: ['https://cloud.flexdz.com/serve/file/i_7tkXXea9DmA5Nw2b-pe-1778007110430.webp'],
  },
  {
    store: 'MoumtazKids', url: 'https://moumtazkids.com/categories',
    name: 'باقة الأرجوحة للأطفال',
    price: '3000', oldPrice: '4500',
    category: 'لوازم الرضيع',
    description: 'باقة أرجوحة أطفال متكاملة لتهدئة الرضيع وتسليته بأمان.',
    images: ['https://cloud.flexdz.com/serve/file/yS0r0nznaUFpNEuDh0eg7-1781547058482.webp'],
  },
  {
    store: 'DoumDoum', url: 'https://www.doumdoum.store/packsoins',
    name: 'باقة العناية الكاملة — Pack Soin Complet',
    price: '1000', oldPrice: '',
    category: 'لوازم الرضيع',
    description: 'باقة عناية كاملة تجمع أساسيات العناية اليومية في حزمة واحدة عملية وبسعر مميز.',
    images: [
      'https://assets.lightfunnels.com/account-70443/images_library/981eccfb-53eb-41c7-a36a-5760d1652a17.GOxNf6E8HH7UAo3s4nVaj.webp',
      'https://assets.lightfunnels.com/account-70443/images_library/ef209b84-48b7-49a7-b38f-c126deb1d6ed.e9P0AJ80SITOXhSsiViby.webp',
      'https://assets.lightfunnels.com/account-70443/images_library/e1479587-8f88-4a5a-a62b-88612111e336.jpClg_ibREn_GVT097QHm.webp',
    ],
  },
  {
    store: 'TopOfferDZ', url: 'https://topofferdz.store/products/orthopediquekangourou',
    name: 'حمّالة الأطفال الطبية — Orthopédique Kangourou',
    price: '3200', oldPrice: '',
    category: 'سفر وتنقل',
    description: 'حمّالة أطفال طبية مريحة توزّع وزن الطفل وتحمي ظهرك من الألم، وتدعم نمو عظام طفلك بشكل صحي. متوفرة بعدة ألوان. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://cdn.youcan.shop/stores/8b505c4c6426063b19d6348df485ac8c/products/rIwmqev3ziQwhXqjbi8ciyJTB6D8L5X7OufXZbes.webp',
      'https://cdn.youcan.shop/stores/8b505c4c6426063b19d6348df485ac8c/products/TRNyt9UeFn5SOUKsw3Htc8GPNT9QkbFZ1usZpTDx.webp',
      'https://cdn.youcan.shop/stores/8b505c4c6426063b19d6348df485ac8c/products/kNmv199DcDh7jSan3m0VJm9MwLKVJ9dJNCWi0zWW.webp',
      'https://cdn.youcan.shop/stores/8b505c4c6426063b19d6348df485ac8c/products/9PjKjROetf7nHy9P1RePOj7HUGeKBjoVuMHpyexW.webp',
    ],
  },
  {
    store: 'Petit Tresor', url: 'https://89ker6-kh.myshopify.com/products/كرسي-هز-للأطفال-الرضع-petit-tresor',
    name: 'كرسي هزّاز للرضّع — Petit Trésor',
    price: '4850', oldPrice: '',
    category: 'لوازم الرضيع',
    description: 'كرسي هزّاز للرضّع بحركة هزّ هادئة تساعد على تهدئة الطفل، مع ألعاب معلّقة تنمّي حواسه ووسادة ناعمة وحزام أمان. عدة ألوان. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://cdn.shopify.com/s/files/1/0795/5598/5508/files/1784106130855.png',
      'https://cdn.shopify.com/s/files/1/0795/5598/5508/files/1784106039974.png',
      'https://cdn.shopify.com/s/files/1/0795/5598/5508/files/1784105208646.png',
      'https://cdn.shopify.com/s/files/1/0795/5598/5508/files/1784105249814.png',
    ],
  },
  {
    store: 'TifliDZ', url: 'https://tiflidz.myecomsite.net/newborn-bed',
    name: 'سرير الأطفال حديثي الولادة متعدّد الاستعمالات',
    price: '2500', oldPrice: '',
    category: 'لوازم الرضيع',
    description: 'سرير عملي متعدّد الاستعمالات للأطفال حديثي الولادة، آمن ومريح لنوم طفلك وأفضل هدية للمولود الجديد. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://assets.lightfunnels.com/account-73970/images_library/eda47c4a-c8a5-4bc4-9046-c49244ac71a0.Final%20Lp1.webp',
      'https://assets.lightfunnels.com/account-73970/images_library/b01caa2e-88d0-434d-99c9-c98d1a9ecf3c.dFiFFqulc68KgcYEiyXXkp5WpKz9PfFA36tOXTqi.webp',
      'https://assets.lightfunnels.com/account-73970/images_library/0ae9892a-4438-4141-a1b5-3ec8d3811279.IMG_8406.webp',
      'https://assets.lightfunnels.com/account-73970/images_library/58902a9f-8313-49bb-b4e5-aeef0bf2a826.IMG_8397.webp',
    ],
  },
  {
    store: 'Sekoon', url: 'https://sekoon.myecomsite.net/WjElXdMbp',
    name: 'وسادة طبية عالية الجودة للحوامل',
    price: '5700', oldPrice: '',
    category: 'راحة الأم',
    description: 'وسادة طبية عالية الجودة للحوامل تدعم الظهر والبطن وتخفّف الضغط، لتمنحك نوماً مريحاً وراحة أكبر طوال فترة الحمل. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://assets.lightfunnels.com/account-80199/images_library/5210c0bb-9012-4596-b8d9-c610b6978c9f.exT1rAN3_vJIyxYoanrXY.webp',
      'https://assets.lightfunnels.com/account-80199/images_library/88c4e15e-c152-44df-8eae-301d2b9480e2.oPhBkKvqcA-6tflNrmw7W.webp',
      'https://assets.lightfunnels.com/account-80199/images_library/530f5f4f-71da-4738-a72f-4ab0719bea6c.rtG05jEQJK0D3pa4UaaeC.webp',
      'https://assets.lightfunnels.com/account-80199/images_library/92304a35-58c7-44ea-b945-17eb6cd85df8.BuuiBjXPz2s0AyvA9SOfZ.webp',
    ],
  },
  {
    store: 'Cleopatre', url: 'https://www.cleopatre.store/category/bracelet-congratulations',
    name: 'أساور أطفال — تذكار المولود (ستانلس ستيل)',
    price: '1900', oldPrice: '2500',
    category: 'تذكارات وهدايا',
    description: 'أساور أطفال أنيقة من الستانلس ستيل، هدية مثالية لتهنئة المولود الجديد. تصاميم متعددة: دبدوب، غيمة، تاج، وHello Kitty. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://cdn.okwin.shop/uploads/698de03c465f9e229027b5eb/image-b4873c0e-58a1-4967-83c8-00df4dab892e-1784512872261.avif',
      'https://cdn.okwin.shop/uploads/698de03c465f9e229027b5eb/image-76fb9dec-8f7e-451a-bbdd-b5edffb5095b-1784681369547.avif',
      'https://cdn.okwin.shop/uploads/698de03c465f9e229027b5eb/image-23171614-e97d-4d13-98a5-55970e5bddf8-1784903955592.avif',
      'https://cdn.okwin.shop/uploads/698de03c465f9e229027b5eb/image-35468de5-19b6-49dc-a566-0001848ea148-1784681010028.avif',
    ],
  },
  {
    store: 'CoucouMaman', url: 'https://coucoumaman.flexdz.store/categories/698b475c362e2acfa2bd280c',
    name: 'علبة طعام كهربائية مسخّنة للأطفال 600 مل',
    price: '2000', oldPrice: '2500',
    category: 'الرضاعة والتغذية',
    description: 'علبة طعام كهربائية تسخّن وجبة طفلك بسرعة وأمان، بسعة 600 مل عملية للخرجات والسفر. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/kPMrGfDYtagDq8iMW7xqR-1770583992174.webp'],
  },
  {
    store: 'CoucouMaman', url: 'https://coucoumaman.flexdz.store/categories/698b475c362e2acfa2bd280c',
    name: 'ترمس حفظ حرارة للأطفال — Kids Heaven',
    price: '1850', oldPrice: '1950',
    category: 'الرضاعة والتغذية',
    description: 'ترمس لحفظ حرارة حليب أو طعام طفلك لساعات، عملي وآمن للاستعمال اليومي وأثناء التنقّل. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/UyvbsHnm3Lq0IZjJpKK3m-1770465624639.webp'],
  },
  {
    store: 'CoucouMaman', url: 'https://coucoumaman.flexdz.store/categories/698b475c362e2acfa2bd280c',
    name: 'علبة تقسيم حليب البودرة للأطفال — Kids Heaven',
    price: '1350', oldPrice: '1750',
    category: 'الرضاعة والتغذية',
    description: 'علبة عملية لتقسيم وحفظ حليب البودرة بجرعات منظّمة، مثالية للخرجات وتحضير الرضعات بسرعة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/8jJfSVuUXmcJS7Sl1LI8L-1770465994510.webp'],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/collier-de-dentition-ambre',
    name: 'قلادة العنبر الطبيعي للتسنين — Collier d ambre',
    price: '3900', oldPrice: '4200',
    category: 'لوازم الرضيع',
    description: 'قلادة من العنبر الطبيعي تساعد على تهدئة آلام التسنين عند الرضيع بطريقة طبيعية وآمنة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://anjim.store/cdn/shop/files/pN9Ab01WXU5vLAk0bsluFt5OHM9Z5YCRHOAlGt4Y_1.webp'],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/ensemble-de-bain-pliable-pour-bebe-baignoire-seau-louche',
    name: 'طقم استحمام قابل للطي للرضيع (بانيو + دلو + مغرفة)',
    price: '4950', oldPrice: '',
    category: 'لوازم الرضيع',
    description: 'طقم استحمام متكامل قابل للطي للرضيع يشمل بانيو ودلو ومغرفة، عملي وموفّر للمساحة وسهل التخزين. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/1_e2063aff-dd43-48ff-a0d2-e28c2bb88271.png',
      'https://anjim.store/cdn/shop/files/fb53f991-a060-441f-94b4-01e63d132b67.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/mommy-bag-premium-1',
    name: 'حقيبة الأمومة الفاخرة — Mommy Bag Premium',
    price: '5500', oldPrice: '',
    category: 'حقيبة الولادة',
    description: 'حقيبة أمومة أنيقة وواسعة لحمل كل مستلزمات طفلك بسهولة، مع حزام قابل للتعديل وجيوب تخزين ومفرش تغيير حفاضات. عدة ألوان. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/1_c59572bb-a2c2-4b7e-8466-a2f30f8c0453.png',
      'https://anjim.store/cdn/shop/files/1_7e0f6953-a971-4e20-b7c2-7c7afd0e1911.png',
      'https://anjim.store/cdn/shop/files/2_79d806a9-003f-4aec-99d1-142ba211979b.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/barboteuse-elegante-avec-t-shirt-pour-bebe',
    name: 'بلوزة أنيقة مع تيشرت للرضيع — Barboteuse',
    price: '2450', oldPrice: '',
    category: 'ملابس المولود',
    description: 'طقم أنيق للرضيع (باربوتيز مع تيشرت) بخامة ناعمة وتصميم عصري، مريح ومناسب للخرجات والمناسبات. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/010.png',
      'https://anjim.store/cdn/shop/files/03.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/robe-kabyle-d-ete-pour-fille-1',
    name: 'فستان قبائلي صيفي للبنات — Robe Kabyle',
    price: '2450', oldPrice: '',
    category: 'ملابس المولود',
    description: 'فستان قبائلي تقليدي أنيق للبنات بتصميم صيفي خفيف ومريح وتطريزات جميلة، مثالي للأعياد والمناسبات. مقاسات من 3 أشهر إلى 24 شهراً. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/Untitleddesign-2026-07-20T111226.476_1b040e9a-b8c8-41cb-bd7e-ff027ca6fa2a.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/robe-kayble',
    name: 'فستان أمازيغي أنيق للبنات — Robe Amazighe',
    price: '4150', oldPrice: '',
    category: 'ملابس المولود',
    description: 'فستان أمازيغي تقليدي بتطريزات ملوّنة راقية مستوحاة من التراث، ناعم ومريح ومثالي للأعياد والأعراس والمناسبات. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/Untitled_design_-_2026-06-15T205623.889.png',
      'https://anjim.store/cdn/shop/files/1_16b5cca8-7e0b-480c-aeb1-046899cc0245.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/salopette-bebe-elegante-avec-body-a-col',
    name: 'سالوبيت أنيقة مع بودي للرضيع — Salopette',
    price: '2300', oldPrice: '',
    category: 'ملابس المولود',
    description: 'طقم أنيق للرضيع يتكوّن من بودي بياقة راقية وسالوبيت، بخامة ناعمة على بشرة الطفل وتصميم عصري مثالي للخرجات والمناسبات. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/2_3cfd83a3-0059-43e7-af21-5a74f7de95f6.png',
      'https://anjim.store/cdn/shop/files/5_8597bdad-1ec4-4d98-bef2-0d0de83c7ebf.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/ensemble-robe-bebe-premium',
    name: 'طقم فستان بيبي فاخر — Ensemble Robe Premium',
    price: '3250', oldPrice: '',
    category: 'ملابس المولود',
    description: 'طقم فستان بيبي أنيق يتكوّن من فستان راقٍ وبودي مريح، بخامة خفيفة ولمسات فاخرة، مثالي لأيام الصيف والمناسبات. عدة ألوان ومقاسات. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/Untitleddesign-2026-05-19T103828.892.png',
      'https://anjim.store/cdn/shop/files/Untitleddesign-2026-05-19T100342.420.png',
    ],
  },
  {
    store: 'AnjimStore', url: 'https://anjim.store/products/ensemble-de-circoncision-luxueux-5-pieces-a-l-elegance-traditionnelle-raffinee',
    name: 'طقم الطهور الفاخر — 5 قطع',
    price: '2600', oldPrice: '3150',
    category: 'ملابس المولود',
    description: 'طقم طهور فاخر مكوّن من 5 قطع بأناقة تقليدية راقية، مثالي لإحياء مناسبة طهور مولودك بأجمل إطلالة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://anjim.store/cdn/shop/files/1_8e79cbee-83cb-4b50-a5e1-55611a12e2f3.png',
      'https://anjim.store/cdn/shop/files/2_c701fba9-1ee9-4ff2-8173-59ea08393cda.png',
    ],
  },
  {
    store: 'ZSStore', url: 'https://zsstoore.com/products/bp-smartbebe',
    name: 'مضخة حليب كهربائية ذكية بشاشة لمس',
    price: '5990', oldPrice: '7899',
    category: 'الرضاعة والتغذية',
    description: 'مضخة حليب كهربائية ذكية بشاشة لمس تتيح تحكّماً دقيقاً في قوة الشفط بوضعيات متعددة، لتجربة رضاعة مريحة وهادئة لكل أم. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://zsstoore.com/cdn/shop/files/fddf.png'],
  },
  {
    store: 'ZSStore', url: 'https://zsstoore.com/products/babyfeed01',
    name: 'طقم تغذية سيليكون للأطفال — 8 قطع',
    price: '4400', oldPrice: '',
    category: 'الرضاعة والتغذية',
    description: 'طقم تغذية للأطفال من 8 قطع سيليكون آمنة (أطباق وملاعق وأدوات)، عملي وسهل التنظيف لبداية تغذية صحية لطفلك. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://zsstoore.com/cdn/shop/files/Baby-SLC-3.jpg',
      'https://zsstoore.com/cdn/shop/files/Baby-SLC-1.jpg',
    ],
  },
  {
    store: 'GaminoBebe', url: 'https://gaminobebe.justsell.store/product/22600',
    name: 'عضّاضة تغذية الفواكه للأطفال — Sucette Fruit',
    price: '2200', oldPrice: '',
    category: 'الرضاعة والتغذية',
    description: 'عضّاضة سيليكون لتغذية الطفل بالفواكه الطازجة أو المجمّدة بأمان، تهدّئ اللثة أثناء التسنين. متوفرة بعدة ألوان. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://media.justsell.store/product-media/responsive/768/d9baf7b0-0b58-49e6-97be-fd3bd6c04b95.jpeg'],
  },
  {
    store: 'Jeux88', url: 'https://jeux88.okwin.shop/p/tirelait011070',
    name: 'شفاط حليب كهربائي — Tire-lait',
    price: '4700', oldPrice: '',
    category: 'الرضاعة والتغذية',
    description: 'شفاط حليب كهربائي عملي وهادئ بمستويات شفط قابلة للتحكّم، يمنح الأم راحة ومرونة في الرضاعة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: [
      'https://cdn.okwin.shop/uploads/67ebec6f128b18390b6c9916/image-aa2a2db3-4c3e-47d5-bf24-116343602fa7-1779550266769.avif',
      'https://cdn.okwin.shop/uploads/67ebec6f128b18390b6c9916/image-7a2148d1-da26-4030-841e-a8227fe6f690-1779550462639.avif',
      'https://cdn.okwin.shop/uploads/67ebec6f128b18390b6c9916/image-81578d7f-12dd-403a-98a0-45a757b091bb-1779550475725.avif',
    ],
  },
  {
    store: 'Dukaa', url: 'https://dukaa.a.ayor.ai/dukaa/monbebee',
    name: 'بدلة النجمة المريحة للأطفال',
    price: '2500', oldPrice: '4900',
    category: 'ملابس المولود',
    description: 'بدلة أطفال مريحة بتصميم النجمة، بخامة ناعمة على بشرة الطفل ومناسبة للاستعمال اليومي. عدة ألوان. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://dukaa.a.ayor.ai/dukaa/MEDIA/image_30233b90-addf-4be6-9350-c22d14606d61_800x800.webp'],
  },
  {
    store: 'FamilyKids', url: 'https://familykids.flexdz.store/',
    name: 'قرونيار بيبي — بيجاما رضيع',
    price: '1950', oldPrice: '',
    category: 'ملابس المولود',
    description: 'قرونيار (بيجاما) للرضيع بخامة قطنية ناعمة ومريحة للنوم واللعب. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/gHPrdyhH1CUY0Q1n7kARx-1784828951244.webp'],
  },
  {
    store: 'FamilyKids', url: 'https://familykids.flexdz.store/',
    name: 'طقم بناتي أنيق — Ensemble Fille',
    price: '1800', oldPrice: '2600',
    category: 'ملابس المولود',
    description: 'طقم بناتي أنيق بخامة مريحة وتصميم عصري، مثالي للخرجات والمناسبات. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/TcvWpo_gUzfeuLqK7XBv7-1784226315202.webp'],
  },
  {
    store: 'FamilyKids', url: 'https://familykids.flexdz.store/',
    name: 'طقم بناتي — Ensemble Fille 2',
    price: '1950', oldPrice: '',
    category: 'ملابس المولود',
    description: 'طقم بناتي بخامة ناعمة وتصميم جميل يمنح طفلتك إطلالة أنيقة ومريحة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/txfBJdCeR56mOizqYbaNT-1784110383908.webp'],
  },
  {
    store: 'FamilyKids', url: 'https://familykids.flexdz.store/',
    name: 'طقم بيبي ولادي — Ensemble Bébé',
    price: '1600', oldPrice: '',
    category: 'ملابس المولود',
    description: 'طقم بيبي ولادي عملي ومريح بخامة قطنية ناعمة، مناسب للاستعمال اليومي. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/_6lgPvo29netDcqN3Uqjf-1784110150558.webp'],
  },
  {
    store: 'FamilyKids', url: 'https://familykids.flexdz.store/',
    name: 'طقم بيبي فاخر — Ensemble Bébé Premium',
    price: '2800', oldPrice: '',
    category: 'ملابس المولود',
    description: 'طقم بيبي فاخر بخامة راقية وتصميم أنيق يمنح طفلك إطلالة مميزة ومريحة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/rhbGqXG98ZEMT9dbnRTWV-1784109899146.webp'],
  },
  {
    store: 'LeMondeDesBebes', url: 'https://lemondedesbebes.boutique/categories/6a68bb611fa514e7f423b078',
    name: 'بيجاما أطفال (بنات وأولاد) — Pyjama',
    price: '950', oldPrice: '',
    category: 'ملابس المولود',
    description: 'بيجاما أطفال قطنية ناعمة ومريحة للنوم، متوفرة للبنات والأولاد بتصاميم جميلة وبسعر مميز. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/TQrdAYcF3CKIbN0zu1IUF-1785249781423.webp'],
  },
  {
    store: 'LeMondeDesBebes', url: 'https://lemondedesbebes.boutique/categories/6a68bb611fa514e7f423b078',
    name: 'بيجاما بناتي — Pyjama Fille',
    price: '950', oldPrice: '',
    category: 'ملابس المولود',
    description: 'بيجاما بناتي ناعمة ومريحة بتصميم أنيق للنوم واللعب، بخامة قطنية لطيفة على البشرة. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/zdp9uCrgGRavqTyQsaQVB-1781029148746.webp'],
  },
  {
    store: 'LeMondeDesBebes', url: 'https://lemondedesbebes.boutique/categories/6a68bb611fa514e7f423b078',
    name: 'بيجاما أطفال مريحة — Pyjama',
    price: '950', oldPrice: '',
    category: 'ملابس المولود',
    description: 'بيجاما أطفال مريحة بخامة قطنية ناعمة وتصميم عملي للنوم اليومي بسعر اقتصادي. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://cloud.flexdz.com/serve/file/1HgOF8nSAnFbeefXkw-ur-1778772411358.webp'],
  },
  {
    store: 'LesAffaires', url: 'https://lesaffaires.a.ayor.ai/lesaffaires/boysave',
    name: 'وسادة الحماية للأطفال (خوذة تعلّم المشي)',
    price: '2900', oldPrice: '',
    category: 'لوازم الرضيع',
    description: 'وسادة حماية ناعمة لرأس وظهر الطفل تحميه من الصدمات أثناء تعلّم الجلوس والمشي. تصاميم لطيفة (النمر، الفيل، النحلة، الأرنوبة). توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://lesaffaires.a.ayor.ai/lesaffaires/MEDIA/image_c2a7a20c-952b-409d-8b9c-ba162ad964b2_400x400.webp'],
  },
  {
    store: 'BabyDola', url: 'https://babydola.a.ayor.ai/babydola/bebe',
    name: 'رضّاعة أطفال بدون استخدام اليدين',
    price: '2800', oldPrice: '',
    category: 'الرضاعة والتغذية',
    description: 'رضّاعة أطفال مبتكرة بدون استخدام اليدين تمنح راحة للأم وللطفل أثناء الرضاعة، بتصميم عملي وآمن. توصيل لكل الولايات والدفع عند الاستلام.',
    images: ['https://babydola.a.ayor.ai/babydola/MEDIA/image_81b8fc1a-dfc9-4f0d-9aa2-a6ebd2d8c3ac.webp'],
  },
];

const out = [];
for (const p of raw) {
  const doc = toNabda(
    { sourceId: p.url, name: p.name, description: p.description, price: p.price, oldPrice: p.oldPrice, images: p.images, url: p.url },
    { name: p.store, defaultCategory: p.category },
    cfg
  );
  if (p.category) doc.category = p.category; // تجاوز يدوي مؤكد
  out.push(doc);
}

fs.writeFileSync(cfg.outputFile, JSON.stringify(out, null, 2), 'utf8');

// ملخص
const byCat = {};
out.forEach((p) => (byCat[p.category] = (byCat[p.category] || 0) + 1));
console.log('إجمالي:', out.length, 'منتج');
console.log('بدون صورة:', out.filter((p) => !p.imageUrl).length, '| بدون سعر:', out.filter((p) => !p.price).length);
console.log('حسب الفئة:');
Object.entries(byCat).sort((a,b)=>b[1]-a[1]).forEach(([c,n]) => console.log('  ' + c + ': ' + n));
console.log('\nعينة:');
out.slice(0,3).forEach((p) => console.log(' -', p.name, '| ' + p.category + ' | ' + p.price + (p.oldPrice?(' (كان '+p.oldPrice+')'):'') + ' | صور:' + p.imageUrls.length + ' | slug:' + p.slug));
