// AUTO-GENERATED: Pregnancy week-by-week articles
// 40 weeks, Arabic + English, comprehensive content

class PregnancyWeekArticle {
  final int week;
  final String babySizeAr;
  final String babySizeEn;
  final String babyLength;
  final String babyWeight;
  final String fetalDevAr;
  final String fetalDevEn;
  final String symptomsAr;
  final String symptomsEn;
  final String nutritionAr;
  final String nutritionEn;
  final String tipsAr;
  final String tipsEn;

  const PregnancyWeekArticle({
    required this.week,
    required this.babySizeAr,
    required this.babySizeEn,
    required this.babyLength,
    required this.babyWeight,
    required this.fetalDevAr,
    required this.fetalDevEn,
    required this.symptomsAr,
    required this.symptomsEn,
    required this.nutritionAr,
    required this.nutritionEn,
    required this.tipsAr,
    required this.tipsEn,
  });

  String getTrimester() {
    if (week <= 12) return 'first';
    if (week <= 27) return 'second';
    return 'third';
  }

  String getTrimesterAr() {
    if (week <= 12) return 'الثلث الأول';
    if (week <= 27) return 'الثلث الثاني';
    return 'الثلث الثالث';
  }

  String getTrimesterEn() {
    if (week <= 12) return 'First Trimester';
    if (week <= 27) return 'Second Trimester';
    return 'Third Trimester';
  }
}

final List<PregnancyWeekArticle> pregnancyWeekArticles = [
  PregnancyWeekArticle(
    week: 1,
    babySizeAr: 'بذرة صغيرة جداً',
    babySizeEn: 'Tiny seed',
    babyLength: '0.1 مم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'يبدأ الأسبوع الأول من آخر دورة شهرية. تقنياً لم يحدث الحمل بعد، لكن الجسم يستعد للإباضة. بطانة الرحم تبدأ بالتجدد استعداداً لاستقبال البويضة المخصبة.',
    fetalDevEn: 'Week 1 starts from the first day of your last period. Technically, conception hasn\'t occurred yet, but your body is preparing for ovulation. The uterine lining begins to renew in preparation for a fertilized egg.',
    symptomsAr: 'أعراض الدورة الشهرية المعتادة: تقلصات خفيفة، نزيف الحيض، تغيرات في المزاج.',
    symptomsEn: 'Typical menstrual symptoms: mild cramps, menstrual bleeding, mood changes.',
    nutritionAr: 'ابدئي بتناول حمض الفوليك (400 ميكروغرام يومياً). أكثري من الخضروات الورقية الداكنة والحبوب الكاملة والفواكه الطازجة.',
    nutritionEn: 'Start taking folic acid (400mcg daily). Increase intake of dark leafy greens, whole grains, and fresh fruits.',
    tipsAr: 'إذا كنتِ تخططين للحمل، توقفي عن التدخين والكحول. ابدئي بتسجيل دورتك الشهرية لمعرفة أيام الإباضة.',
    tipsEn: 'If planning pregnancy, stop smoking and alcohol. Start tracking your menstrual cycle to identify ovulation days.',
  ),
  PregnancyWeekArticle(
    week: 2,
    babySizeAr: 'بذرة الخشخاش',
    babySizeEn: 'Poppy seed',
    babyLength: '0.1 مم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'تحدث الإباضة عادةً في منتصف الدورة. البويضة تنطلق من المبيض وتنتقل عبر قناة فالوب. إذا التقت بحيوان منوي، يحدث الإخصاب وتبدأ رحلة الحمل.',
    fetalDevEn: 'Ovulation typically occurs mid-cycle. The egg is released from the ovary and travels through the fallopian tube. If it meets a sperm, fertilization occurs and the pregnancy journey begins.',
    symptomsAr: 'قد تشعرين بألم خفيف في أحد جانبي البطن (ألم الإباضة). زيادة في الإفرازات المهبلية الشفافة.',
    symptomsEn: 'You may feel mild pain on one side of the abdomen (ovulation pain). Increased clear vaginal discharge.',
    nutritionAr: 'استمري في تناول حمض الفوليك. تناولي أطعمة غنية بالحديد مثل السبانخ واللحوم الحمراء والعدس.',
    nutritionEn: 'Continue folic acid. Eat iron-rich foods like spinach, red meat, and lentils.',
    tipsAr: 'هذا هو الوقت الأمثل للحمل. حافظي على نمط حياة صحي وتجنبي الإجهاد الشديد.',
    tipsEn: 'This is the optimal time for conception. Maintain a healthy lifestyle and avoid excessive stress.',
  ),
  PregnancyWeekArticle(
    week: 3,
    babySizeAr: 'بذرة الخشخاش',
    babySizeEn: 'Poppy seed',
    babyLength: '0.2 مم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'البويضة المخصبة تنقسم بسرعة لتشكل كتلة من الخلايا تسمى التوتية (Morula). تنتقل عبر قناة فالوب نحو الرحم. بنهاية الأسبوع تصبح كيسة أريمية (Blastocyst) جاهزة للانغراس.',
    fetalDevEn: 'The fertilized egg divides rapidly to form a cell cluster called a morula. It travels through the fallopian tube toward the uterus. By week\'s end, it becomes a blastocyst ready for implantation.',
    symptomsAr: 'قد لا تشعرين بأي أعراض بعد. بعض النساء يشعرن بنزيف خفيف جداً عند الانغراس.',
    symptomsEn: 'You may not feel any symptoms yet. Some women experience very light spotting during implantation.',
    nutritionAr: 'تناولي البروتينات الصحية: البيض، الدجاج، السمك، البقوليات. اشربي كمية كافية من الماء (8 أكواب يومياً).',
    nutritionEn: 'Eat healthy proteins: eggs, chicken, fish, legumes. Drink enough water (8 glasses daily).',
    tipsAr: 'تجنبي الأدوية غير الموصوفة من الطبيب. قللي من الكافيين إلى أقل من 200 ملغ يومياً.',
    tipsEn: 'Avoid non-prescribed medications. Limit caffeine to less than 200mg daily.',
  ),
  PregnancyWeekArticle(
    week: 4,
    babySizeAr: 'بذرة الخشخاش',
    babySizeEn: 'Poppy seed',
    babyLength: '1 مم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'الكيسة الأريمية تنغرس في بطانة الرحم. تبدأ المشيمة بالتشكل وتنتج هرمون HCG الذي يمكن كشفه في اختبار الحمل. الطبقات الثلاث للجنين تبدأ بالتكون: الأديم الظاهر والمتوسط والباطن.',
    fetalDevEn: 'The blastocyst implants in the uterine lining. The placenta begins forming and produces HCG hormone detectable in pregnancy tests. Three embryonic layers start forming: ectoderm, mesoderm, and endoderm.',
    symptomsAr: 'تأخر الدورة الشهرية — أول علامة واضحة. غثيان خفيف، تعب شديد، ألم في الثديين، تقلبات مزاجية.',
    symptomsEn: 'Missed period — first clear sign. Mild nausea, severe fatigue, breast tenderness, mood swings.',
    nutritionAr: 'زيدي من تناول الكالسيوم: الحليب، الزبادي، الجبن. حمض الفوليك ضروري جداً لمنع عيوب الأنبوب العصبي.',
    nutritionEn: 'Increase calcium intake: milk, yogurt, cheese. Folic acid is crucial to prevent neural tube defects.',
    tipsAr: 'يمكنكِ إجراء اختبار الحمل المنزلي الآن. إذا كانت النتيجة إيجابية، حددي موعداً مع طبيب النساء والتوليد.',
    tipsEn: 'You can take a home pregnancy test now. If positive, schedule an appointment with an OB-GYN.',
  ),
  PregnancyWeekArticle(
    week: 5,
    babySizeAr: 'حبة سمسم',
    babySizeEn: 'Sesame seed',
    babyLength: '2 مم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'قلب الجنين الصغير يبدأ بالنبض! الأنبوب العصبي الذي سيصبح الدماغ والحبل الشوكي يتشكل. براعم صغيرة تظهر حيث ستنمو الذراعان والساقان.',
    fetalDevEn: 'The tiny heart begins to beat! The neural tube that will become the brain and spinal cord forms. Small buds appear where arms and legs will grow.',
    symptomsAr: 'غثيان الصباح يزداد، تعب شديد، كثرة التبول، حساسية للروائح، انتفاخ البطن.',
    symptomsEn: 'Morning sickness increases, severe fatigue, frequent urination, sensitivity to smells, bloating.',
    nutritionAr: 'تناولي وجبات صغيرة ومتكررة لتخفيف الغثيان. أكثري من الزنجبيل والبسكويت المملح. تجنبي الأطعمة الدهنية.',
    nutritionEn: 'Eat small, frequent meals to reduce nausea. Try ginger and salty crackers. Avoid fatty foods.',
    tipsAr: 'الراحة مهمة جداً. لا تقلقي من الغثيان — فهو علامة على أن هرمونات الحمل تعمل بشكل جيد.',
    tipsEn: 'Rest is very important. Don\'t worry about nausea — it\'s a sign that pregnancy hormones are working well.',
  ),
  PregnancyWeekArticle(
    week: 6,
    babySizeAr: 'حبة عدس',
    babySizeEn: 'Lentil',
    babyLength: '6 مم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'الوجه يبدأ بالتشكل مع نقاط داكنة حيث ستكون العينان. فتحات الأنف والأذنان تبدأ بالظهور. القلب ينبض بمعدل 110 نبضة في الدقيقة. الكليتان والكبد يبدآن بالتطور.',
    fetalDevEn: 'The face begins forming with dark spots where eyes will be. Nostrils and ears start appearing. Heart beats at 110 BPM. Kidneys and liver begin developing.',
    symptomsAr: 'غثيان شديد، إرهاق، دوخة، صداع، تقلبات مزاجية حادة، رغبة أو نفور من أطعمة معينة.',
    symptomsEn: 'Severe nausea, exhaustion, dizziness, headaches, intense mood swings, food cravings or aversions.',
    nutritionAr: 'فيتامين B6 يساعد في تخفيف الغثيان. تناولي الموز والأفوكادو والمكسرات. اشربي عصير الليمون الطازج.',
    nutritionEn: 'Vitamin B6 helps reduce nausea. Eat bananas, avocado, and nuts. Drink fresh lemon juice.',
    tipsAr: 'تجنبي اللحوم النيئة والأجبان غير المبسترة والأسماك عالية الزئبق. اغسلي الفواكه والخضروات جيداً.',
    tipsEn: 'Avoid raw meat, unpasteurized cheese, and high-mercury fish. Wash fruits and vegetables thoroughly.',
  ),
  PregnancyWeekArticle(
    week: 7,
    babySizeAr: 'حبة توت',
    babySizeEn: 'Blueberry',
    babyLength: '1.3 سم',
    babyWeight: 'أقل من 1 غرام',
    fetalDevAr: 'الدماغ ينمو بسرعة كبيرة — حوالي 100 خلية عصبية جديدة كل دقيقة! أصابع اليدين والقدمين تبدأ بالتشكل وإن كانت متصلة. عدسات العينين تتكون.',
    fetalDevEn: 'The brain grows rapidly — about 100 new nerve cells every minute! Fingers and toes begin forming though still webbed. Eye lenses are forming.',
    symptomsAr: 'استمرار الغثيان، زيادة إفراز اللعاب، إمساك، حرقة المعدة، زيادة حجم الثديين.',
    symptomsEn: 'Continued nausea, excess saliva, constipation, heartburn, breast enlargement.',
    nutritionAr: 'أكثري من الألياف لمكافحة الإمساك: الشوفان، الفواكه، الخضروات. اشربي 10 أكواب ماء يومياً.',
    nutritionEn: 'Increase fiber to fight constipation: oats, fruits, vegetables. Drink 10 glasses of water daily.',
    tipsAr: 'ارتدي حمالة صدر مريحة. مارسي المشي الخفيف يومياً. نامي مبكراً واحصلي على 8 ساعات نوم.',
    tipsEn: 'Wear a comfortable bra. Walk lightly daily. Sleep early and get 8 hours of sleep.',
  ),
  PregnancyWeekArticle(
    week: 8,
    babySizeAr: 'حبة فاصوليا',
    babySizeEn: 'Kidney bean',
    babyLength: '1.6 سم',
    babyWeight: '1 غرام',
    fetalDevAr: 'الجنين يتحرك باستمرار لكنكِ لا تشعرين به بعد. الأصابع تنفصل عن بعضها. الأنف والشفة العليا والجفون تتشكل. الذيل الجنيني يختفي تقريباً.',
    fetalDevEn: 'The embryo moves constantly but you can\'t feel it yet. Fingers separate. Nose, upper lip, and eyelids form. The embryonic tail almost disappears.',
    symptomsAr: 'غثيان مستمر، تعب شديد، احتقان الأنف، أحلام واضحة وغريبة، تقلصات خفيفة في الرحم.',
    symptomsEn: 'Persistent nausea, severe fatigue, nasal congestion, vivid dreams, mild uterine cramps.',
    nutritionAr: 'تناولي أوميغا 3 لتطور دماغ الجنين: السلمون، الجوز، بذور الشيا. استمري بحمض الفوليك والحديد.',
    nutritionEn: 'Take omega-3 for fetal brain development: salmon, walnuts, chia seeds. Continue folic acid and iron.',
    tipsAr: 'حددي موعد أول زيارة لطبيب النساء إذا لم تفعلي. ستسمعين نبض قلب الجنين لأول مرة!',
    tipsEn: 'Schedule your first OB-GYN visit if you haven\'t. You\'ll hear the baby\'s heartbeat for the first time!',
  ),
  PregnancyWeekArticle(
    week: 9,
    babySizeAr: 'حبة عنب',
    babySizeEn: 'Grape',
    babyLength: '2.3 سم',
    babyWeight: '2 غرام',
    fetalDevAr: 'الجنين أصبح الآن جنيناً بالكامل (Fetus). جميع الأعضاء الرئيسية موجودة وتتطور. الأصابع مكتملة. العضلات تبدأ بالعمل. يمكنه ثني ذراعيه.',
    fetalDevEn: 'The embryo is now officially a fetus. All major organs are present and developing. Fingers are complete. Muscles begin working. Can bend arms.',
    symptomsAr: 'قد يبدأ الغثيان بالتحسن تدريجياً. زيادة في الوزن بسيطة. تقلبات مزاجية. رغبة شديدة في أطعمة معينة.',
    symptomsEn: 'Nausea may gradually improve. Slight weight gain. Mood swings. Strong food cravings.',
    nutritionAr: 'فيتامين C مهم لامتصاص الحديد: البرتقال، الفراولة، الفلفل. تناولي منتجات الألبان للكالسيوم.',
    nutritionEn: 'Vitamin C is important for iron absorption: oranges, strawberries, peppers. Eat dairy for calcium.',
    tipsAr: 'تجنبي حمل الأشياء الثقيلة. ابدئي بالتفكير في الفحوصات الجينية إذا كنتِ ترغبين.',
    tipsEn: 'Avoid lifting heavy objects. Start thinking about genetic screening if desired.',
  ),
  PregnancyWeekArticle(
    week: 10,
    babySizeAr: 'حبة زيتون',
    babySizeEn: 'Olive',
    babyLength: '3.1 سم',
    babyWeight: '4 غرام',
    fetalDevAr: 'أصابع القدمين تنفصل. العظام تبدأ بالتصلب. الأعضاء التناسلية تبدأ بالتمايز (لكن لا يمكن تحديد الجنس بعد). الكليتان تنتجان البول.',
    fetalDevEn: 'Toes separate. Bones begin hardening. Reproductive organs start differentiating (but gender can\'t be determined yet). Kidneys produce urine.',
    symptomsAr: 'انتفاخ البطن يزداد. الأوردة تظهر بوضوح في الثديين. تعب مستمر لكن الغثيان يتحسن.',
    symptomsEn: 'Bloating increases. Veins become visible on breasts. Continued fatigue but nausea improves.',
    nutritionAr: 'ابدئي بزيادة السعرات تدريجياً (حوالي 300 سعرة إضافية يومياً). ركزي على البروتين والحبوب الكاملة.',
    nutritionEn: 'Start gradually increasing calories (about 300 extra daily). Focus on protein and whole grains.',
    tipsAr: 'مارسي تمارين كيجل لتقوية عضلات الحوض. ارتدي ملابس مريحة وواسعة.',
    tipsEn: 'Practice Kegel exercises to strengthen pelvic muscles. Wear comfortable, loose clothing.',
  ),
  PregnancyWeekArticle(
    week: 11,
    babySizeAr: 'حبة تين',
    babySizeEn: 'Fig',
    babyLength: '4.1 سم',
    babyWeight: '7 غرام',
    fetalDevAr: 'الرأس يشكل نصف طول الجسم. براعم الأسنان تتكون تحت اللثة. الأظافر تبدأ بالنمو. يمكنه فتح وإغلاق قبضتيه.',
    fetalDevEn: 'Head makes up half the body length. Tooth buds form under gums. Nails start growing. Can open and close fists.',
    symptomsAr: 'الجوع يزداد. الشعر والأظافر تنمو أسرع. حب الشباب قد يظهر. بداية ظهور خط أسود على البطن.',
    symptomsEn: 'Hunger increases. Hair and nails grow faster. Acne may appear. Dark line on belly may start showing.',
    nutritionAr: 'تناولي وجبات خفيفة صحية بين الوجبات: المكسرات، الفواكه المجففة، الزبادي. الزنك مهم: اللحوم، البقوليات.',
    nutritionEn: 'Eat healthy snacks between meals: nuts, dried fruits, yogurt. Zinc is important: meats, legumes.',
    tipsAr: 'ابدئي بالتخطيط لإخبار عائلتك بالحمل. الخطر الأكبر للإجهاض ينتهي بعد الأسبوع 12.',
    tipsEn: 'Start planning to share pregnancy news with family. The highest miscarriage risk ends after week 12.',
  ),
  PregnancyWeekArticle(
    week: 12,
    babySizeAr: 'حبة ليمون',
    babySizeEn: 'Lime',
    babyLength: '5.4 سم',
    babyWeight: '14 غرام',
    fetalDevAr: 'جميع الأعضاء تكونت وتبدأ بالنضج. الوجه مكتمل الملامح. ردود الفعل تعمل — يمكنه المص والبلع. الكلى تعمل بكفاءة.',
    fetalDevEn: 'All organs are formed and begin maturing. Face has full features. Reflexes work — can suck and swallow. Kidneys work efficiently.',
    symptomsAr: 'الغثيان يبدأ بالاختفاء عند معظم النساء! الطاقة تعود تدريجياً. خطر الإجهاض ينخفض كثيراً.',
    symptomsEn: 'Nausea starts disappearing for most women! Energy gradually returns. Miscarriage risk drops significantly.',
    nutritionAr: 'احتفلي بنهاية الثلث الأول! تناولي أطعمة غنية بفيتامين D: السمك، البيض، التعرض المعتدل للشمس.',
    nutritionEn: 'Celebrate the end of the first trimester! Eat vitamin D-rich foods: fish, eggs, moderate sun exposure.',
    tipsAr: 'موعد الفحص النووي (NT scan) لتقييم صحة الجنين. أخبري مديرك في العمل إذا أردتِ.',
    tipsEn: 'Time for the nuchal translucency (NT) scan. Tell your employer if you wish.',
  ),
  PregnancyWeekArticle(
    week: 13,
    babySizeAr: 'حبة خوخ',
    babySizeEn: 'Peach',
    babyLength: '7.4 سم',
    babyWeight: '23 غرام',
    fetalDevAr: 'بداية الثلث الثاني — الفترة الذهبية! بصمات الأصابع الفريدة تتكون. الحبال الصوتية تتطور. إذا كان الجنين أنثى، المبيضان يحتويان أكثر من 2 مليون بويضة.',
    fetalDevEn: 'Start of the second trimester — the golden period! Unique fingerprints form. Vocal cords develop. If female, ovaries contain over 2 million eggs.',
    symptomsAr: 'الطاقة تعود بقوة! الشهية تزداد. قد يظهر ألم في الأربطة المستديرة (ألم حاد في أسفل البطن عند الحركة).',
    symptomsEn: 'Energy returns strongly! Appetite increases. Round ligament pain may appear (sharp lower belly pain with movement).',
    nutritionAr: 'زيدي من البروتين لنمو الجنين السريع. تناولي اللحوم المطبوخة جيداً، الأسماك، البيض، العدس.',
    nutritionEn: 'Increase protein for rapid fetal growth. Eat well-cooked meats, fish, eggs, lentils.',
    tipsAr: 'هذا وقت رائع لممارسة الرياضة الخفيفة: المشي، السباحة، اليوغا للحوامل.',
    tipsEn: 'Great time for light exercise: walking, swimming, prenatal yoga.',
  ),
  PregnancyWeekArticle(
    week: 14,
    babySizeAr: 'حبة ليمون كبيرة',
    babySizeEn: 'Lemon',
    babyLength: '8.7 سم',
    babyWeight: '43 غرام',
    fetalDevAr: 'يمكنه تحريك عضلات الوجه — التكشير والعبوس! الشعر الناعم (الزغب) يبدأ بتغطية الجسم. الغدة الدرقية تنتج الهرمونات. يمكنه التبول.',
    fetalDevEn: 'Can move facial muscles — grimacing and frowning! Fine hair (lanugo) starts covering the body. Thyroid produces hormones. Can urinate.',
    symptomsAr: 'زيادة الطاقة والشهية. قد تلاحظين تغيراً في لون الجلد (كلف الحمل). احتقان الأنف.',
    symptomsEn: 'Increased energy and appetite. You may notice skin color changes (pregnancy mask). Nasal congestion.',
    nutritionAr: 'المغنيسيوم مهم لمنع التشنجات: الموز، المكسرات، الشوكولاتة الداكنة، السبانخ.',
    nutritionEn: 'Magnesium is important to prevent cramps: bananas, nuts, dark chocolate, spinach.',
    tipsAr: 'ابدئي بالنوم على جانبك الأيسر. هذا يحسن تدفق الدم للمشيمة والجنين.',
    tipsEn: 'Start sleeping on your left side. This improves blood flow to the placenta and baby.',
  ),
  PregnancyWeekArticle(
    week: 15,
    babySizeAr: 'تفاحة',
    babySizeEn: 'Apple',
    babyLength: '10.1 سم',
    babyWeight: '70 غرام',
    fetalDevAr: 'يمكنه الشعور بالضوء رغم أن عينيه مغلقتان. العظام تتصلب أكثر. يتدرب على التنفس عن طريق استنشاق السائل الأمنيوسي.',
    fetalDevEn: 'Can sense light even though eyes are closed. Bones harden further. Practices breathing by inhaling amniotic fluid.',
    symptomsAr: 'قد تشعرين بأولى حركات الجنين (رفرفة خفيفة). البطن يبدأ بالظهور بوضوح. ألم الظهر قد يبدأ.',
    symptomsEn: 'You may feel first fetal movements (light fluttering). Belly starts showing clearly. Back pain may begin.',
    nutritionAr: 'الكالسيوم ضروري لعظام الجنين: الحليب، اللبن، الجبن، السردين. فيتامين K من الخضروات الورقية.',
    nutritionEn: 'Calcium is essential for fetal bones: milk, yogurt, cheese, sardines. Vitamin K from leafy greens.',
    tipsAr: 'ابدئي بالبحث عن ملابس الحمل المريحة. فكري في دورات تحضير الولادة.',
    tipsEn: 'Start looking for comfortable maternity clothes. Consider childbirth preparation classes.',
  ),
  PregnancyWeekArticle(
    week: 16,
    babySizeAr: 'حبة أفوكادو',
    babySizeEn: 'Avocado',
    babyLength: '11.6 سم',
    babyWeight: '100 غرام',
    fetalDevAr: 'يمكنه سماع صوتك! الأذن الداخلية تعمل. العينان تتحركان خلف الجفون. الجهاز العصبي يتطور بسرعة. يمكن تحديد الجنس بالسونار.',
    fetalDevEn: 'Can hear your voice! Inner ear works. Eyes move behind eyelids. Nervous system develops rapidly. Gender can be determined via ultrasound.',
    symptomsAr: 'حركات الجنين أوضح. زيادة الوزن ملحوظة. الأوردة تظهر بوضوح. قد تشعرين بضيق في التنفس.',
    symptomsEn: 'Fetal movements are clearer. Noticeable weight gain. Veins become visible. You may feel shortness of breath.',
    nutritionAr: 'أوميغا 3 لتطور الدماغ والعينين: السلمون، الجوز، بذور الكتان. تجنبي الأسماك عالية الزئبق.',
    nutritionEn: 'Omega-3 for brain and eye development: salmon, walnuts, flaxseed. Avoid high-mercury fish.',
    tipsAr: 'تحدثي مع جنينك وأسمعيه الموسيقى الهادئة. القرآن الكريم له تأثير مهدئ رائع.',
    tipsEn: 'Talk to your baby and play soft music. Quran recitation has a wonderful calming effect.',
  ),
  PregnancyWeekArticle(
    week: 17,
    babySizeAr: 'حبة رمان',
    babySizeEn: 'Pomegranate',
    babyLength: '13 سم',
    babyWeight: '140 غرام',
    fetalDevAr: 'الدهون تبدأ بالتراكم تحت الجلد لتنظيم حرارة الجسم. المشيمة تنمو لتوفير المزيد من الغذاء. الحبل السري يصبح أقوى وأسمك.',
    fetalDevEn: 'Fat begins accumulating under the skin for body temperature regulation. Placenta grows to provide more nutrition. Umbilical cord becomes stronger and thicker.',
    symptomsAr: 'قد تعانين من نزيف اللثة عند تنظيف الأسنان. زيادة العرق. أحلام حية وغريبة.',
    symptomsEn: 'You may experience bleeding gums when brushing. Increased sweating. Vivid, strange dreams.',
    nutritionAr: 'الحديد ضروري لمنع فقر الدم: اللحوم الحمراء، السبانخ، العدس. تناوليه مع فيتامين C لامتصاص أفضل.',
    nutritionEn: 'Iron is essential to prevent anemia: red meat, spinach, lentils. Take with vitamin C for better absorption.',
    tipsAr: 'احجزي موعد فحص السونار التفصيلي (Anatomy scan) الذي يكون عادة في الأسبوع 18-20.',
    tipsEn: 'Schedule the detailed anatomy scan ultrasound, usually done at weeks 18-20.',
  ),
  PregnancyWeekArticle(
    week: 18,
    babySizeAr: 'حبة فلفل',
    babySizeEn: 'Bell pepper',
    babyLength: '14.2 سم',
    babyWeight: '190 غرام',
    fetalDevAr: 'يمكنه التثاؤب والحازوقة! الأعصاب تُغلف بمادة الميالين لنقل الإشارات بسرعة. إذا كان أنثى، الرحم وقناتا فالوب في مكانهما.',
    fetalDevEn: 'Can yawn and hiccup! Nerves are coated with myelin for faster signal transmission. If female, uterus and fallopian tubes are in place.',
    symptomsAr: 'حركات الجنين واضحة ومنتظمة أكثر. ألم الظهر يزداد. تورم خفيف في القدمين.',
    symptomsEn: 'Fetal movements are clearer and more regular. Back pain increases. Mild foot swelling.',
    nutritionAr: 'البوتاسيوم يقلل التورم: الموز، البطاطا الحلوة، الأفوكادو. اشربي الماء بكثرة.',
    nutritionEn: 'Potassium reduces swelling: bananas, sweet potatoes, avocado. Drink plenty of water.',
    tipsAr: 'ارفعي قدميك عند الجلوس. تجنبي الوقوف لفترات طويلة. ارتدي أحذية مريحة.',
    tipsEn: 'Elevate your feet when sitting. Avoid standing for long periods. Wear comfortable shoes.',
  ),
  PregnancyWeekArticle(
    week: 19,
    babySizeAr: 'حبة مانجو',
    babySizeEn: 'Mango',
    babyLength: '15.3 سم',
    babyWeight: '240 غرام',
    fetalDevAr: 'طبقة واقية بيضاء (الطلاء الجبني) تغطي الجلد لحمايته من السائل الأمنيوسي. الحواس الخمس تتطور. الدماغ يحدد مناطق متخصصة للحواس.',
    fetalDevEn: 'A protective white coating (vernix caseosa) covers the skin to protect it from amniotic fluid. Five senses develop. Brain designates specialized sensory areas.',
    symptomsAr: 'الشهية كبيرة! الجلد يتمدد وقد يظهر حكة. بداية ظهور علامات التمدد.',
    symptomsEn: 'Big appetite! Skin stretches and may itch. Stretch marks may start appearing.',
    nutritionAr: 'زيت الزيتون وزبدة الشيا على البطن لترطيب الجلد. فيتامين E من المكسرات والبذور.',
    nutritionEn: 'Olive oil and shea butter on belly to moisturize skin. Vitamin E from nuts and seeds.',
    tipsAr: 'رطبي بطنك يومياً لتقليل علامات التمدد. استمتعي بحركات طفلك!',
    tipsEn: 'Moisturize your belly daily to reduce stretch marks. Enjoy your baby\'s movements!',
  ),
  PregnancyWeekArticle(
    week: 20,
    babySizeAr: 'موزة',
    babySizeEn: 'Banana',
    babyLength: '16.4 سم',
    babyWeight: '300 غرام',
    fetalDevAr: 'نصف الحمل! الجنين يبتلع السائل الأمنيوسي ويتذوقه. الجهاز الهضمي ينتج العقي (أول براز). الأظافر مكتملة.',
    fetalDevEn: 'Halfway there! Baby swallows amniotic fluid and tastes it. Digestive system produces meconium (first stool). Nails are complete.',
    symptomsAr: 'البطن واضح جداً. ضيق التنفس عند المجهود. حرقة المعدة. تشنجات في الساقين ليلاً.',
    symptomsEn: 'Belly is very visible. Shortness of breath with exertion. Heartburn. Leg cramps at night.',
    nutritionAr: 'تناولي وجبات صغيرة ومتكررة لتقليل الحرقة. تجنبي الأطعمة الحارة والحمضية قبل النوم.',
    nutritionEn: 'Eat small, frequent meals to reduce heartburn. Avoid spicy and acidic foods before bed.',
    tipsAr: 'فحص السونار التفصيلي (Anatomy scan) — ستشاهدين جنينك بالتفصيل وقد تعرفين جنسه!',
    tipsEn: 'Detailed anatomy scan — you\'ll see your baby in detail and may learn the gender!',
  ),
  PregnancyWeekArticle(
    week: 21,
    babySizeAr: 'جزرة كبيرة',
    babySizeEn: 'Large carrot',
    babyLength: '26.7 سم',
    babyWeight: '360 غرام',
    fetalDevAr: 'الحواجب والرموش تنمو. يتحرك كثيراً ويركل بقوة. نمط النوم والاستيقاظ يبدأ بالتكون. يمكنه التعرف على صوتك.',
    fetalDevEn: 'Eyebrows and eyelashes grow. Moves a lot and kicks strongly. Sleep-wake pattern begins forming. Can recognize your voice.',
    symptomsAr: 'انقباضات براكستون هيكس (تقلصات تدريبية غير مؤلمة). زيادة الإفرازات المهبلية. حكة في البطن.',
    symptomsEn: 'Braxton Hicks contractions (painless practice contractions). Increased vaginal discharge. Belly itching.',
    nutritionAr: 'البروتين ضروري لنمو العضلات: الدجاج، السمك، البيض، الحمص. فيتامين A من الجزر والبطاطا الحلوة.',
    nutritionEn: 'Protein is essential for muscle growth: chicken, fish, eggs, chickpeas. Vitamin A from carrots and sweet potatoes.',
    tipsAr: 'ابدئي بالتخطيط لغرفة الطفل. فكري في الأسماء! هذه فترة ممتعة.',
    tipsEn: 'Start planning the nursery. Think about names! This is a fun time.',
  ),
  PregnancyWeekArticle(
    week: 22,
    babySizeAr: 'حبة بابايا',
    babySizeEn: 'Papaya',
    babyLength: '27.8 سم',
    babyWeight: '430 غرام',
    fetalDevAr: 'العينان تكونتا لكن القزحية لا تحتوي على لون بعد. اللمس متطور — يمسك الحبل السري ويلمس وجهه. البنكرياس ينضج.',
    fetalDevEn: 'Eyes are formed but iris has no color yet. Touch is developed — grabs umbilical cord and touches face. Pancreas matures.',
    symptomsAr: 'آلام الظهر تزداد. تورم القدمين واليدين. صعوبة النوم. زيادة ملحوظة في الوزن.',
    symptomsEn: 'Back pain increases. Swelling in feet and hands. Difficulty sleeping. Noticeable weight gain.',
    nutritionAr: 'الألياف لمنع الإمساك: الحبوب الكاملة، الفواكه، الخضروات. اشربي 12 كوب ماء يومياً.',
    nutritionEn: 'Fiber to prevent constipation: whole grains, fruits, vegetables. Drink 12 glasses of water daily.',
    tipsAr: 'نامي على جانبك الأيسر مع وسادة بين الركبتين. تمارين التمدد تخفف ألم الظهر.',
    tipsEn: 'Sleep on your left side with a pillow between knees. Stretching exercises relieve back pain.',
  ),
  PregnancyWeekArticle(
    week: 23,
    babySizeAr: 'حبة باذنجان',
    babySizeEn: 'Eggplant',
    babyLength: '28.9 سم',
    babyWeight: '500 غرام',
    fetalDevAr: 'يسمع الأصوات الخارجية بوضوح: صوتك، الموسيقى، حتى أصوات البيئة المحيطة. الرئتان تتدربان على التنفس. الجلد لا يزال شفافاً ومتجعداً.',
    fetalDevEn: 'Hears external sounds clearly: your voice, music, even environmental sounds. Lungs practice breathing. Skin is still transparent and wrinkled.',
    symptomsAr: 'زيادة الشهية. حركة الجنين قوية ومنتظمة. قد تشعرين بالحازوقة (نبضات منتظمة في البطن).',
    symptomsEn: 'Increased appetite. Strong, regular fetal movement. You may feel hiccups (regular pulsing in belly).',
    nutritionAr: 'DHA أوميغا 3 ضروري لنمو الدماغ: السلمون، السردين، بذور الشيا. تجنبي التونة الكبيرة.',
    nutritionEn: 'DHA omega-3 is essential for brain growth: salmon, sardines, chia seeds. Avoid large tuna.',
    tipsAr: 'اقرئي القرآن والكتب بصوت عالٍ — جنينك يسمعك ويتعرف على صوتك!',
    tipsEn: 'Read Quran and books aloud — your baby hears you and recognizes your voice!',
  ),
  PregnancyWeekArticle(
    week: 24,
    babySizeAr: 'كوز ذرة',
    babySizeEn: 'Ear of corn',
    babyLength: '30 سم',
    babyWeight: '600 غرام',
    fetalDevAr: 'الرئتان تنتجان مادة السرفاكتانت التي تمنع الرئتين من الالتصاق. إذا وُلد الآن، لديه فرصة للبقاء بالعناية المركزة. بصمات الأصابع والقدمين مكتملة.',
    fetalDevEn: 'Lungs produce surfactant that prevents them from sticking together. If born now, has a chance of survival with intensive care. Fingerprints and footprints are complete.',
    symptomsAr: 'ألم في أسفل الظهر وعظام الحوض. تورم القدمين بنهاية اليوم. صعوبة في إيجاد وضعية نوم مريحة.',
    symptomsEn: 'Lower back and pelvic bone pain. Foot swelling by end of day. Difficulty finding comfortable sleeping position.',
    nutritionAr: 'الكالسيوم والفوسفور لعظام الجنين: منتجات الألبان، اللوز، البروكلي. فيتامين D ضروري.',
    nutritionEn: 'Calcium and phosphorus for fetal bones: dairy products, almonds, broccoli. Vitamin D is essential.',
    tipsAr: 'ابدئي بفحص سكري الحمل (Glucose test). تعلمي علامات الولادة المبكرة.',
    tipsEn: 'Start gestational diabetes screening (Glucose test). Learn signs of premature labor.',
  ),
  PregnancyWeekArticle(
    week: 25,
    babySizeAr: 'حبة شمندر كبيرة',
    babySizeEn: 'Large beetroot',
    babyLength: '34.6 سم',
    babyWeight: '660 غرام',
    fetalDevAr: 'الشعر ينمو على الرأس وقد يكون له لون! الدهون تتراكم تحت الجلد فيصبح أقل شفافية. يتجاوب مع اللمس — إذا ضغطتِ على بطنك قد يركل!',
    fetalDevEn: 'Hair grows on the head and may have color! Fat accumulates under skin making it less transparent. Responds to touch — if you press your belly, baby may kick!',
    symptomsAr: 'البواسير قد تظهر. الشخير أثناء النوم. تشنجات الساقين ليلاً. الرغبة المتكررة في التبول.',
    symptomsEn: 'Hemorrhoids may appear. Snoring during sleep. Nighttime leg cramps. Frequent urination urge.',
    nutritionAr: 'الألياف والماء لمنع البواسير. المغنيسيوم لتشنجات الساقين: المكسرات، الموز، البذور.',
    nutritionEn: 'Fiber and water to prevent hemorrhoids. Magnesium for leg cramps: nuts, bananas, seeds.',
    tipsAr: 'لا تقفي لفترات طويلة. حمام دافئ قبل النوم يخفف التشنجات والتوتر.',
    tipsEn: 'Don\'t stand for long periods. A warm bath before bed relieves cramps and tension.',
  ),
  PregnancyWeekArticle(
    week: 26,
    babySizeAr: 'كوسة كبيرة',
    babySizeEn: 'Large zucchini',
    babyLength: '35.6 سم',
    babyWeight: '760 غرام',
    fetalDevAr: 'العينان تفتحان لأول مرة! يمكنه الرمش. يتفاعل مع الضوء الساطع. الرئتان تستمران في النضج. نمط النوم واضح (ينام 18-20 ساعة يومياً).',
    fetalDevEn: 'Eyes open for the first time! Can blink. Reacts to bright light. Lungs continue maturing. Clear sleep pattern (sleeps 18-20 hours daily).',
    symptomsAr: 'ضيق التنفس يزداد. آلام الضلوع بسبب توسع الرحم. صعوبة الانحناء. الأرق.',
    symptomsEn: 'Shortness of breath increases. Rib pain from uterine expansion. Difficulty bending. Insomnia.',
    nutritionAr: 'وجبات صغيرة ومتكررة لتقليل ضيق التنفس. البروتين في كل وجبة لنمو الجنين السريع.',
    nutritionEn: 'Small, frequent meals to reduce breathlessness. Protein in every meal for rapid fetal growth.',
    tipsAr: 'جهزي حقيبة المستشفى مبكراً. تعرفي على قسم الولادة في المستشفى الذي اخترتِه.',
    tipsEn: 'Pack your hospital bag early. Familiarize yourself with the delivery ward at your chosen hospital.',
  ),
  PregnancyWeekArticle(
    week: 27,
    babySizeAr: 'حبة قرنبيط',
    babySizeEn: 'Cauliflower',
    babyLength: '36.6 سم',
    babyWeight: '875 غرام',
    fetalDevAr: 'نهاية الثلث الثاني! الدماغ نشط جداً — يحلم! يمكنه فتح وإغلاق عينيه. يتعرف على صوت الأم والأب. الرئتان تقتربان من النضج.',
    fetalDevEn: 'End of second trimester! Brain is very active — dreams! Can open and close eyes. Recognizes mother\'s and father\'s voice. Lungs approach maturity.',
    symptomsAr: 'الحازوقة المنتظمة عند الجنين. تقلصات براكستون هيكس أكثر. تعب وثقل في الجسم.',
    symptomsEn: 'Regular fetal hiccups. More Braxton Hicks contractions. Fatigue and body heaviness.',
    nutritionAr: 'الحديد مهم جداً في الثلث الأخير — الجنين يخزن الحديد لأول 6 أشهر بعد الولادة.',
    nutritionEn: 'Iron is very important in the third trimester — baby stores iron for the first 6 months after birth.',
    tipsAr: 'ابدئي بدورة تحضير الولادة. تعلمي تقنيات التنفس والاسترخاء.',
    tipsEn: 'Start a childbirth preparation course. Learn breathing and relaxation techniques.',
  ),
  PregnancyWeekArticle(
    week: 28,
    babySizeAr: 'حبة باذنجان كبيرة',
    babySizeEn: 'Large eggplant',
    babyLength: '37.6 سم',
    babyWeight: '1 كغ',
    fetalDevAr: 'بداية الثلث الثالث! يمكنه الحلم (نشاط REM). الرموش كاملة. يتدرب على التنفس بانتظام. يزداد وزنه بسرعة من الآن.',
    fetalDevEn: 'Start of the third trimester! Can dream (REM activity). Eyelashes complete. Practices breathing regularly. Gains weight rapidly from now.',
    symptomsAr: 'ألم الظهر شديد. تورم القدمين والكاحلين. صعوبة النوم. ضيق التنفس عند أي مجهود.',
    symptomsEn: 'Severe back pain. Swollen feet and ankles. Difficulty sleeping. Shortness of breath with any exertion.',
    nutritionAr: 'زيدي من السعرات 300-500 سعرة إضافية. البروتين والكالسيوم والحديد أولوية قصوى.',
    nutritionEn: 'Increase calories by 300-500 extra. Protein, calcium, and iron are top priority.',
    tipsAr: 'زيارات الطبيب تصبح كل أسبوعين. تعلمي علامات الولادة المبكرة.',
    tipsEn: 'Doctor visits become biweekly. Learn signs of premature labor.',
  ),
  PregnancyWeekArticle(
    week: 29,
    babySizeAr: 'قرع صغير',
    babySizeEn: 'Small butternut squash',
    babyLength: '38.6 سم',
    babyWeight: '1.2 كغ',
    fetalDevAr: 'العظام مكتملة لكنها لينة. الدماغ يتحكم في حرارة الجسم. يمكنه التمييز بين النور والظلام. يكتسب دهوناً أكثر.',
    fetalDevEn: 'Bones are complete but soft. Brain controls body temperature. Can distinguish between light and dark. Gains more fat.',
    symptomsAr: 'تقلصات براكستون هيكس أقوى. صعوبة في المشي. كثرة التبول. حرقة المعدة.',
    symptomsEn: 'Stronger Braxton Hicks contractions. Difficulty walking. Frequent urination. Heartburn.',
    nutritionAr: 'فيتامين C لتقوية المناعة: البرتقال، الكيوي، الفراولة. البروتين في كل وجبة.',
    nutritionEn: 'Vitamin C for immunity: oranges, kiwi, strawberries. Protein in every meal.',
    tipsAr: 'ابدئي بعد حركات الجنين يومياً (10 حركات في ساعتين على الأقل).',
    tipsEn: 'Start counting fetal movements daily (at least 10 movements in 2 hours).',
  ),
  PregnancyWeekArticle(
    week: 30,
    babySizeAr: 'ملفوفة',
    babySizeEn: 'Cabbage',
    babyLength: '39.9 سم',
    babyWeight: '1.3 كغ',
    fetalDevAr: 'الجنين محاط بنصف لتر من السائل الأمنيوسي (سيقل تدريجياً). نخاع العظام ينتج خلايا الدم الحمراء. الدماغ يتطور بسرعة مذهلة.',
    fetalDevEn: 'Baby is surrounded by half a liter of amniotic fluid (will gradually decrease). Bone marrow produces red blood cells. Brain develops at amazing speed.',
    symptomsAr: 'التعب الشديد يعود. أرق ليلي. ألم في الأضلاع. صعوبة في التنفس عند الاستلقاء.',
    symptomsEn: 'Severe fatigue returns. Night insomnia. Rib pain. Difficulty breathing when lying down.',
    nutritionAr: 'وجبات صغيرة كل 2-3 ساعات. التمر غني بالحديد والألياف ومفيد للولادة. اشربي الحليب يومياً.',
    nutritionEn: 'Small meals every 2-3 hours. Dates are rich in iron and fiber and beneficial for labor. Drink milk daily.',
    tipsAr: 'نامي بوسائد متعددة لدعم الظهر والبطن. مارسي تمارين التنفس يومياً.',
    tipsEn: 'Sleep with multiple pillows to support back and belly. Practice breathing exercises daily.',
  ),
  PregnancyWeekArticle(
    week: 31,
    babySizeAr: 'جوز هند',
    babySizeEn: 'Coconut',
    babyLength: '41.1 سم',
    babyWeight: '1.5 كغ',
    fetalDevAr: 'الدماغ يعالج المعلومات من الحواس الخمس. يتبع دورة نوم منتظمة. يمكنه تحريك رأسه. الرئتان تنضجان أكثر.',
    fetalDevEn: 'Brain processes information from all five senses. Follows regular sleep cycle. Can move head. Lungs mature further.',
    symptomsAr: 'حركة الجنين قد تقل قليلاً لأنه أصبح كبيراً. ركلات قوية ومؤلمة أحياناً. تسرب حليب من الثديين.',
    symptomsEn: 'Fetal movement may slightly decrease as baby grows bigger. Strong, sometimes painful kicks. Breast milk leakage.',
    nutritionAr: 'تناولي التمر يومياً (3-6 حبات). البروتين والكالسيوم ضروريان. تناولي الأطعمة الغنية بالحديد.',
    nutritionEn: 'Eat dates daily (3-6 pieces). Protein and calcium are essential. Eat iron-rich foods.',
    tipsAr: 'جهزي قائمة بمستلزمات الطفل. ابدئي بشراء الأساسيات: سرير، ملابس، حفاضات.',
    tipsEn: 'Prepare a list of baby essentials. Start buying basics: crib, clothes, diapers.',
  ),
  PregnancyWeekArticle(
    week: 32,
    babySizeAr: 'كوسة كبيرة جداً',
    babySizeEn: 'Large squash',
    babyLength: '42.4 سم',
    babyWeight: '1.7 كغ',
    fetalDevAr: 'أظافر القدمين مكتملة. الجلد أصبح ناعماً وأقل تجعداً بفضل الدهون. يتدرب على البلع والتنفس والمص — استعداداً للرضاعة!',
    fetalDevEn: 'Toenails complete. Skin becomes smooth and less wrinkled thanks to fat. Practices swallowing, breathing, and sucking — preparing for breastfeeding!',
    symptomsAr: 'ثقل شديد في أسفل البطن. صعوبة في النوم والمشي. تورم القدمين. حرقة شديدة.',
    symptomsEn: 'Severe heaviness in lower belly. Difficulty sleeping and walking. Swollen feet. Severe heartburn.',
    nutritionAr: 'وجبات خفيفة قبل النوم لتقليل الحرقة. تجنبي الاستلقاء بعد الأكل مباشرة. اللبن الرائب مفيد.',
    nutritionEn: 'Light snacks before bed to reduce heartburn. Avoid lying down right after eating. Yogurt is helpful.',
    tipsAr: 'اكتبي خطة الولادة: هل تفضلين ولادة طبيعية أم قيصرية؟ من سيرافقك؟',
    tipsEn: 'Write your birth plan: do you prefer natural or cesarean delivery? Who will accompany you?',
  ),
  PregnancyWeekArticle(
    week: 33,
    babySizeAr: 'أناناس',
    babySizeEn: 'Pineapple',
    babyLength: '43.7 سم',
    babyWeight: '1.9 كغ',
    fetalDevAr: 'العظام تتصلب بشكل كامل ما عدا الجمجمة (تبقى مرنة للمرور عبر قناة الولادة). المناعة تنتقل من الأم إلى الجنين.',
    fetalDevEn: 'Bones fully harden except the skull (stays flexible for birth canal passage). Immunity transfers from mother to baby.',
    symptomsAr: 'انقباضات براكستون هيكس أكثر تكراراً. الأرق شديد. كثرة التبول. ضغط على المثانة.',
    symptomsEn: 'Braxton Hicks contractions more frequent. Severe insomnia. Frequent urination. Bladder pressure.',
    nutritionAr: 'استمري بالتمر والحليب. فيتامينات ما قبل الولادة ضرورية. اشربي شاي التوت الأحمر (يقوي الرحم).',
    nutritionEn: 'Continue with dates and milk. Prenatal vitamins are essential. Drink red raspberry leaf tea (strengthens uterus).',
    tipsAr: 'تعلمي أوضاع الرضاعة الطبيعية. جهزي مستلزمات الرضاعة.',
    tipsEn: 'Learn breastfeeding positions. Prepare breastfeeding supplies.',
  ),
  PregnancyWeekArticle(
    week: 34,
    babySizeAr: 'شمام صغير',
    babySizeEn: 'Small cantaloupe',
    babyLength: '45 سم',
    babyWeight: '2.1 كغ',
    fetalDevAr: 'الرئتان شبه مكتملتين. الجهاز المناعي يعمل بشكل مستقل. الطلاء الجبني يزداد سمكاً. معظم الأجنة يتخذون وضعية الرأس للأسفل.',
    fetalDevEn: 'Lungs are nearly complete. Immune system works independently. Vernix thickens. Most babies assume head-down position.',
    symptomsAr: 'ضغط شديد على الحوض. صعوبة في التنفس. الشعور بأن الجنين نزل للأسفل.',
    symptomsEn: 'Severe pelvic pressure. Difficulty breathing. Feeling that baby has dropped lower.',
    nutritionAr: 'استمري بالتغذية المتوازنة. الدهون الصحية مهمة لدماغ الجنين: زيت الزيتون، الأفوكادو، المكسرات.',
    nutritionEn: 'Continue balanced nutrition. Healthy fats are important for fetal brain: olive oil, avocado, nuts.',
    tipsAr: 'زيارات الطبيب تصبح أسبوعية من الآن. تأكدي أن حقيبة المستشفى جاهزة.',
    tipsEn: 'Doctor visits become weekly from now. Make sure your hospital bag is ready.',
  ),
  PregnancyWeekArticle(
    week: 35,
    babySizeAr: 'شمام',
    babySizeEn: 'Honeydew melon',
    babyLength: '46.2 سم',
    babyWeight: '2.4 كغ',
    fetalDevAr: 'الدماغ يزداد حجمه بثلث حجمه الحالي. الكليتان مكتملتان. الكبد يعمل بكفاءة. معظم التطور الجسدي اكتمل — الآن يزداد وزناً.',
    fetalDevEn: 'Brain increases by a third of its current size. Kidneys complete. Liver works efficiently. Most physical development is complete — now gaining weight.',
    symptomsAr: 'نزول الجنين في الحوض (Lightening) — التنفس أسهل لكن الضغط على المثانة أكثر. تعب شديد.',
    symptomsEn: 'Baby drops into pelvis (Lightening) — breathing is easier but more bladder pressure. Severe fatigue.',
    nutritionAr: 'وجبات غنية بالطاقة: التمر، المكسرات، العسل، الحبوب الكاملة. الترطيب مهم جداً.',
    nutritionEn: 'Energy-rich meals: dates, nuts, honey, whole grains. Hydration is very important.',
    tipsAr: 'راجعي خطة الولادة مع طبيبك. تأكدي من معرفة الطريق إلى المستشفى.',
    tipsEn: 'Review your birth plan with your doctor. Make sure you know the way to the hospital.',
  ),
  PregnancyWeekArticle(
    week: 36,
    babySizeAr: 'خس كبير',
    babySizeEn: 'Large romaine lettuce',
    babyLength: '47.4 سم',
    babyWeight: '2.6 كغ',
    fetalDevAr: 'الزغب (الشعر الناعم) يتساقط. الجنين يبتلع الزغب والسائل الأمنيوسي — يصبح جزءاً من أول براز (العقي). مستعد تقريباً للولادة!',
    fetalDevEn: 'Lanugo (fine hair) sheds. Baby swallows lanugo and amniotic fluid — becomes part of first stool (meconium). Almost ready for birth!',
    symptomsAr: 'ضغط شديد أسفل الحوض. إفرازات مخاطية أكثر. تقلصات أقوى. أرق وقلق.',
    symptomsEn: 'Severe pressure at bottom of pelvis. More mucous discharge. Stronger contractions. Insomnia and anxiety.',
    nutritionAr: 'تناولي 6 حبات تمر يومياً — أثبتت الدراسات أنه يسهل الولادة. استمري بالبروتين والكالسيوم.',
    nutritionEn: 'Eat 6 dates daily — studies show it facilitates labor. Continue with protein and calcium.',
    tipsAr: 'جهزي كل شيء: حقيبة المستشفى، ملابس الطفل، مقعد السيارة. أبلغي مديرك عن موعد إجازة الأمومة.',
    tipsEn: 'Prepare everything: hospital bag, baby clothes, car seat. Inform your employer about maternity leave.',
  ),
  PregnancyWeekArticle(
    week: 37,
    babySizeAr: 'سلق سويسري',
    babySizeEn: 'Swiss chard bunch',
    babyLength: '48.6 سم',
    babyWeight: '2.9 كغ',
    fetalDevAr: 'الجنين مكتمل النمو (Full term)! الرئتان جاهزتان للتنفس. يمكنه الإمساك بإحكام. يتدرب على حركات التنفس. رأسه قد استقر في الحوض.',
    fetalDevEn: 'Baby is full term! Lungs are ready to breathe. Can grasp firmly. Practices breathing movements. Head has settled in pelvis.',
    symptomsAr: 'فقدان السدادة المخاطية (إفراز مخاطي كثيف). تقلصات منتظمة أكثر. طاقة مفاجئة (غريزة التعشيش).',
    symptomsEn: 'Mucous plug loss (thick mucous discharge). More regular contractions. Sudden energy (nesting instinct).',
    nutritionAr: 'استمري بالتمر والتغذية الجيدة. اشربي شاي التوت الأحمر. وجبات خفيفة ومغذية.',
    nutritionEn: 'Continue with dates and good nutrition. Drink red raspberry leaf tea. Light, nutritious meals.',
    tipsAr: 'كوني جاهزة! الولادة قد تحدث في أي وقت. تعلمي الفرق بين المخاض الحقيقي والكاذب.',
    tipsEn: 'Be ready! Labor can happen anytime. Learn the difference between true and false labor.',
  ),
  PregnancyWeekArticle(
    week: 38,
    babySizeAr: 'بطيخة صغيرة',
    babySizeEn: 'Small watermelon',
    babyLength: '49.8 سم',
    babyWeight: '3.1 كغ',
    fetalDevAr: 'الطلاء الجبني بدأ يتلاشى. الأمعاء تتراكم فيها المادة الخضراء الداكنة (العقي). الدماغ والرئتان يستمران في النضج حتى اللحظة الأخيرة.',
    fetalDevEn: 'Vernix starts dissolving. Intestines accumulate dark green substance (meconium). Brain and lungs continue maturing until the last moment.',
    symptomsAr: 'إسهال خفيف (الجسم يتحضر). ألم أسفل الظهر مستمر. تقلصات أقوى وأطول. صعوبة في النوم.',
    symptomsEn: 'Mild diarrhea (body preparing). Persistent lower back pain. Stronger, longer contractions. Difficulty sleeping.',
    nutritionAr: 'وجبات خفيفة وسهلة الهضم. تجنبي الوجبات الكبيرة. اشربي الماء بكثرة.',
    nutritionEn: 'Light, easily digestible meals. Avoid large meals. Drink plenty of water.',
    tipsAr: 'اعرفي علامات بدء المخاض: تقلصات منتظمة كل 5 دقائق، نزول الماء، نزيف خفيف.',
    tipsEn: 'Know signs of labor onset: regular contractions every 5 minutes, water breaking, light bleeding.',
  ),
  PregnancyWeekArticle(
    week: 39,
    babySizeAr: 'بطيخة',
    babySizeEn: 'Watermelon',
    babyLength: '50.7 سم',
    babyWeight: '3.3 كغ',
    fetalDevAr: 'مستعد تماماً للولادة! كل الأعضاء مكتملة. يكتسب المزيد من الدهون للتدفئة بعد الولادة. المضادات الحيوية تنتقل من الأم عبر المشيمة.',
    fetalDevEn: 'Fully ready for birth! All organs complete. Gains more fat for warmth after birth. Antibodies transfer from mother through placenta.',
    symptomsAr: 'تقلصات قوية ومتكررة. الشعور بثقل شديد. نزول الماء قد يحدث. قلق وتوتر طبيعي.',
    symptomsEn: 'Strong, frequent contractions. Feeling very heavy. Water may break. Normal anxiety and tension.',
    nutritionAr: 'تناولي التمر والعسل للطاقة. اشربي الماء. وجبات خفيفة كل ساعتين.',
    nutritionEn: 'Eat dates and honey for energy. Drink water. Light snacks every 2 hours.',
    tipsAr: 'حافظي على الهدوء والاسترخاء. مارسي التنفس العميق. اتصلي بالمستشفى إذا بدأت التقلصات المنتظمة.',
    tipsEn: 'Stay calm and relaxed. Practice deep breathing. Call the hospital if regular contractions start.',
  ),
  PregnancyWeekArticle(
    week: 40,
    babySizeAr: 'يقطينة صغيرة',
    babySizeEn: 'Small pumpkin',
    babyLength: '51.2 سم',
    babyWeight: '3.5 كغ',
    fetalDevAr: 'موعد الولادة المتوقع! الجنين مكتمل تماماً ومستعد لرؤية العالم. الرأس قد يكون مغطى بالشعر. الأظافر قد تكون طويلة. مستعد للحياة خارج الرحم!',
    fetalDevEn: 'Due date! Baby is fully developed and ready to see the world. Head may be covered with hair. Nails may be long. Ready for life outside the womb!',
    symptomsAr: 'علامات المخاض: تقلصات منتظمة كل 5 دقائق لمدة ساعة، نزول السائل الأمنيوسي، نزول السدادة المخاطية مع دم.',
    symptomsEn: 'Labor signs: regular contractions every 5 minutes for an hour, amniotic fluid leaking, bloody mucous plug discharge.',
    nutritionAr: 'وجبات خفيفة للطاقة أثناء المخاض المبكر. عسل وتمر وماء. تجنبي الوجبات الثقيلة.',
    nutritionEn: 'Light snacks for energy during early labor. Honey, dates, and water. Avoid heavy meals.',
    tipsAr: 'ألف مبروك! أنتِ على وشك مقابلة طفلك. ثقي بجسمك وبالله. اتصلي بالمستشفى عند بدء المخاض الحقيقي. أنتِ أم رائعة!',
    tipsEn: 'Congratulations! You\'re about to meet your baby. Trust your body and trust in God. Call the hospital when true labor begins. You\'re an amazing mother!',
  ),
];