// GENERATED — خريطة عنوان المقال → صورته
// DO NOT EDIT BY HAND.
// 359 مقالاً من 389: 221 من المطابقة اليدوية + 138 بالربط التلقائي

const Map<String, String> kArticleImageMap = {
  'التطور الجسدي والحركي للطفل في الشهر الأول': 'assets/images/article_pics/a004.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الأول': 'assets/images/article_pics/a208.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الأول': 'assets/images/article_pics/a337.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الأول': 'assets/images/article_pics/a352.png',
  'صحة الطفل والسلامة المنزلية في الشهر الأول': 'assets/images/article_pics/a002.png',
  'التطور الجسدي والحركي للطفل في الشهر الثاني': 'assets/images/article_pics/a357.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الثاني': 'assets/images/article_pics/a331.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الثاني': 'assets/images/article_pics/a179.png',
  'التطور الجسدي والحركي للطفل في الشهر الثالث': 'assets/images/article_pics/a323.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الثالث': 'assets/images/article_pics/a339.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الثالث': 'assets/images/article_pics/a354.png',
  'صحة الطفل والسلامة المنزلية في الشهر الثالث': 'assets/images/article_pics/a316.png',
  'التطور الجسدي والحركي للطفل في الشهر الرابع': 'assets/images/articles/cat_baby_names.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الرابع': 'assets/images/article_pics/a017.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الرابع': 'assets/images/articles/cat_colic.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الرابع': 'assets/images/article_pics/a333.png',
  'التطور الجسدي والحركي للطفل في الشهر الخامس': 'assets/images/article_pics/a001.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الخامس': 'assets/images/article_pics/a328.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الخامس': 'assets/images/article_pics/x009.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الخامس': 'assets/images/articles/cat_growth_0_6.png',
  'صحة الطفل والسلامة المنزلية في الشهر الخامس': 'assets/images/article_pics/a344.png',
  'التطور الجسدي والحركي للطفل في الشهر السادس': 'assets/images/article_pics/a308.png',
  'التغذية السليمة وإطعام الرضيع في الشهر السادس': 'assets/images/article_pics/a027.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر السادس': 'assets/images/article_pics/a028.png',
  'التطور الجسدي والحركي للطفل في الشهر السابع': 'assets/images/article_pics/x011.png',
  'التغذية السليمة وإطعام الرضيع في الشهر السابع': 'assets/images/article_pics/a032.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر السابع': 'assets/images/article_pics/a033.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر السابع': 'assets/images/article_pics/a034.png',
  'صحة الطفل والسلامة المنزلية في الشهر السابع': 'assets/images/articles/cat_home_safety.png',
  'التطور الجسدي والحركي للطفل في الشهر الثامن': 'assets/images/articles/cat_growth_6_12.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الثامن': 'assets/images/articles/cat_first_foods.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الثامن': 'assets/images/article_pics/a038.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الثامن': 'assets/images/article_pics/a039.png',
  'صحة الطفل والسلامة المنزلية في الشهر الثامن': 'assets/images/article_pics/a320.png',
  'التطور الجسدي والحركي للطفل في الشهر التاسع': 'assets/images/article_pics/x006.png',
  'التغذية السليمة وإطعام الرضيع في الشهر التاسع': 'assets/images/article_pics/a042.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر التاسع': 'assets/images/article_pics/a043.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر التاسع': 'assets/images/article_pics/a044.png',
  'صحة الطفل والسلامة المنزلية في الشهر التاسع': 'assets/images/article_pics/a345.png',
  'التطور الجسدي والحركي للطفل في الشهر العاشر': 'assets/images/article_pics/a046.png',
  'التغذية السليمة وإطعام الرضيع في الشهر العاشر': 'assets/images/article_pics/a047.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر العاشر': 'assets/images/article_pics/a048.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر العاشر': 'assets/images/article_pics/a049.png',
  'صحة الطفل والسلامة المنزلية في الشهر العاشر': 'assets/images/article_pics/a050.png',
  'التطور الجسدي والحركي للطفل في الشهر الحادي عشر': 'assets/images/article_pics/a341.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الحادي عشر': 'assets/images/article_pics/a052.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الحادي عشر': 'assets/images/article_pics/a053.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الحادي عشر': 'assets/images/article_pics/a054.png',
  'صحة الطفل والسلامة المنزلية في الشهر الحادي عشر': 'assets/images/article_pics/a329.png',
  'التطور الجسدي والحركي للطفل في الشهر الثاني عشر': 'assets/images/article_pics/a056.png',
  'التغذية السليمة وإطعام الرضيع في الشهر الثاني عشر': 'assets/images/article_pics/a057.png',
  'تنظيم نوم الرضيع وتأسيس روتين هادئ في الشهر الثاني عشر': 'assets/images/article_pics/a058.png',
  'تطوير الحواس والمهارات الإدراكية للرضيع في الشهر الثاني عشر': 'assets/images/article_pics/a059.png',
  'صحة الطفل والسلامة المنزلية في الشهر الثاني عشر': 'assets/images/article_pics/a300.png',
  'النمو البدني والتطور الحركي للطفل في سن 1 سنوات': 'assets/images/article_pics/a061.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 1 سنوات': 'assets/images/article_pics/a062.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 1 سنوات': 'assets/images/article_pics/a275.png',
  'التعليم والإدراك والتطور الذهني في سن 1 سنوات': 'assets/images/article_pics/a064.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 1 سنوات': 'assets/images/article_pics/a340.png',
  'النمو البدني والتطور الحركي للطفل في سن 2 سنوات': 'assets/images/articles/cat_growth_chart.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 2 سنوات': 'assets/images/article_pics/a187.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 2 سنوات': 'assets/images/article_pics/a068.png',
  'التعليم والإدراك والتطور الذهني في سن 2 سنوات': 'assets/images/articles/cat_reading.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 2 سنوات': 'assets/images/article_pics/a070.png',
  'النمو البدني والتطور الحركي للطفل في سن 3 سنوات': 'assets/images/article_pics/a071.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 3 سنوات': 'assets/images/articles/cat_weaning.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 3 سنوات': 'assets/images/article_pics/a073.png',
  'التعليم والإدراك والتطور الذهني في سن 3 سنوات': 'assets/images/article_pics/a074.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 3 سنوات': 'assets/images/article_pics/a075.png',
  'النمو البدني والتطور الحركي للطفل في سن 4 سنوات': 'assets/images/article_pics/a076.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 4 سنوات': 'assets/images/article_pics/a077.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 4 سنوات': 'assets/images/article_pics/a078.png',
  'التعليم والإدراك والتطور الذهني في سن 4 سنوات': 'assets/images/article_pics/a079.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 4 سنوات': 'assets/images/article_pics/a080.png',
  'النمو البدني والتطور الحركي للطفل في سن 5 سنوات': 'assets/images/article_pics/a081.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 5 سنوات': 'assets/images/article_pics/a082.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 5 سنوات': 'assets/images/article_pics/a083.png',
  'التعليم والإدراك والتطور الذهني في سن 5 سنوات': 'assets/images/article_pics/a084.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 5 سنوات': 'assets/images/article_pics/a085.png',
  'النمو البدني والتطور الحركي للطفل في سن 6 سنوات': 'assets/images/article_pics/a086.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 6 سنوات': 'assets/images/article_pics/a087.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 6 سنوات': 'assets/images/article_pics/a088.png',
  'التعليم والإدراك والتطور الذهني في سن 6 سنوات': 'assets/images/article_pics/a089.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 6 سنوات': 'assets/images/article_pics/a090.png',
  'النمو البدني والتطور الحركي للطفل في سن 7 سنوات': 'assets/images/article_pics/a091.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 7 سنوات': 'assets/images/article_pics/a092.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 7 سنوات': 'assets/images/article_pics/a093.png',
  'التعليم والإدراك والتطور الذهني في سن 7 سنوات': 'assets/images/article_pics/a094.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 7 سنوات': 'assets/images/article_pics/a095.png',
  'النمو البدني والتطور الحركي للطفل في سن 8 سنوات': 'assets/images/article_pics/a096.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 8 سنوات': 'assets/images/article_pics/a097.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 8 سنوات': 'assets/images/article_pics/a098.png',
  'التعليم والإدراك والتطور الذهني في سن 8 سنوات': 'assets/images/article_pics/a099.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 8 سنوات': 'assets/images/article_pics/a100.png',
  'النمو البدني والتطور الحركي للطفل في سن 9 سنوات': 'assets/images/article_pics/a101.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 9 سنوات': 'assets/images/article_pics/a102.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 9 سنوات': 'assets/images/article_pics/a103.png',
  'التعليم والإدراك والتطور الذهني في سن 9 سنوات': 'assets/images/article_pics/a104.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 9 سنوات': 'assets/images/article_pics/a105.png',
  'النمو البدني والتطور الحركي للطفل في سن 10 سنوات': 'assets/images/article_pics/a106.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 10 سنوات': 'assets/images/article_pics/a107.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 10 سنوات': 'assets/images/article_pics/a108.png',
  'التعليم والإدراك والتطور الذهني في سن 10 سنوات': 'assets/images/article_pics/a109.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 10 سنوات': 'assets/images/article_pics/a110.png',
  'النمو البدني والتطور الحركي للطفل في سن 11 سنوات': 'assets/images/article_pics/a111.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 11 سنوات': 'assets/images/article_pics/a112.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 11 سنوات': 'assets/images/article_pics/a113.png',
  'التعليم والإدراك والتطور الذهني في سن 11 سنوات': 'assets/images/article_pics/a114.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 11 سنوات': 'assets/images/article_pics/a115.png',
  'النمو البدني والتطور الحركي للطفل في سن 12 سنوات': 'assets/images/article_pics/a116.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 12 سنوات': 'assets/images/article_pics/a117.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 12 سنوات': 'assets/images/article_pics/a118.png',
  'التعليم والإدراك والتطور الذهني في سن 12 سنوات': 'assets/images/article_pics/a119.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 12 سنوات': 'assets/images/article_pics/a120.png',
  'النمو البدني والتطور الحركي للطفل في سن 13 سنوات': 'assets/images/article_pics/a121.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 13 سنوات': 'assets/images/article_pics/a122.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 13 سنوات': 'assets/images/article_pics/a123.png',
  'التعليم والإدراك والتطور الذهني في سن 13 سنوات': 'assets/images/article_pics/a124.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 13 سنوات': 'assets/images/article_pics/a125.png',
  'النمو البدني والتطور الحركي للطفل في سن 14 سنوات': 'assets/images/article_pics/a126.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 14 سنوات': 'assets/images/article_pics/a127.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 14 سنوات': 'assets/images/article_pics/a128.png',
  'التعليم والإدراك والتطور الذهني في سن 14 سنوات': 'assets/images/article_pics/a129.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 14 سنوات': 'assets/images/article_pics/a130.png',
  'النمو البدني والتطور الحركي للطفل في سن 15 سنوات': 'assets/images/article_pics/a131.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 15 سنوات': 'assets/images/article_pics/a132.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 15 سنوات': 'assets/images/article_pics/a133.png',
  'التعليم والإدراك والتطور الذهني في سن 15 سنوات': 'assets/images/article_pics/a134.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 15 سنوات': 'assets/images/article_pics/a135.png',
  'النمو البدني والتطور الحركي للطفل في سن 16 سنوات': 'assets/images/article_pics/a136.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 16 سنوات': 'assets/images/article_pics/a137.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 16 سنوات': 'assets/images/article_pics/a138.png',
  'التعليم والإدراك والتطور الذهني في سن 16 سنوات': 'assets/images/article_pics/a139.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 16 سنوات': 'assets/images/article_pics/a140.png',
  'النمو البدني والتطور الحركي للطفل في سن 17 سنوات': 'assets/images/article_pics/a141.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 17 سنوات': 'assets/images/article_pics/a142.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 17 سنوات': 'assets/images/article_pics/a143.png',
  'التعليم والإدراك والتطور الذهني في سن 17 سنوات': 'assets/images/article_pics/a144.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 17 سنوات': 'assets/images/article_pics/a145.png',
  'النمو البدني والتطور الحركي للطفل في سن 18 سنوات': 'assets/images/article_pics/a146.png',
  'التغذية المتوازنة والعادات الصحية للطفل في سن 18 سنوات': 'assets/images/article_pics/a147.png',
  'النمو النفسي وتعديل السلوك للطفل في سن 18 سنوات': 'assets/images/article_pics/a148.png',
  'التعليم والإدراك والتطور الذهني في سن 18 سنوات': 'assets/images/article_pics/a149.png',
  'العلاقات الاجتماعية وإدارة الشاشات بأمان في سن 18 سنوات': 'assets/images/article_pics/a150.png',
  'أذكار الحامل اليومية': 'assets/images/article_pics/a151.png',
  'أدعية الولادة الميسّرة': 'assets/images/article_pics/a152.png',
  'أحكام الصلاة للحامل والنفساء': 'assets/images/article_pics/a153.png',
  'الصيام للحامل والمرضع': 'assets/images/article_pics/a183.png',
  'بركة الرضاعة الطبيعية في الإسلام': 'assets/images/article_pics/a155.png',
  'تربية الأطفال على المحبّة في الإسلام': 'assets/images/article_pics/a156.png',
  'تعليم الطفل الوضوء والصلاة': 'assets/images/article_pics/a157.png',
  'أسماء أولاد وبنات إسلامية بمعانيها': 'assets/images/article_pics/a158.png',
  'أذكار حفظ الأطفال من العين والحسد': 'assets/images/article_pics/a159.png',
  'حقّ الأم على ابنها في الإسلام': 'assets/images/article_pics/a160.png',
  'الحمل بتوأم: نظرة شاملة وأنواعه': 'assets/images/article_pics/a161.png',
  'تغذية الحامل بتوأم': 'assets/images/article_pics/a162.png',
  'متابعة حمل التوأم ومخاطره المحتملة': 'assets/images/article_pics/a163.png',
  'رضاعة التوأم والعناية بهما في الأشهر الأولى': 'assets/images/article_pics/a164.png',
  'سيكولوجية تربية التوائم والترابط الفردي': 'assets/images/articles/cat_baby_sleep.png',
  'الاستعداد لولادة التوأم': 'assets/images/article_pics/a166.png',
  'سكري الحمل: ما هو ولماذا يحدث': 'assets/images/article_pics/a167.png',
  'النظام الغذائي لسكري الحمل': 'assets/images/article_pics/a168.png',
  'مراقبة سكر الدم في المنزل': 'assets/images/article_pics/a169.png',
  'النشاط البدني وسكري الحمل': 'assets/images/article_pics/a170.png',
  'متى تحتاجين دواءً أو إنسولين والمتابعة': 'assets/images/article_pics/a219.png',
  'سكري الحمل بعد الولادة والوقاية مستقبلًا': 'assets/images/article_pics/a172.png',
  'ارتفاع ضغط الدم في الحمل: أنواعه وأسبابه': 'assets/images/article_pics/a210.png',
  'التغذية ونمط الحياة لخفض الضغط في الحمل': 'assets/images/article_pics/a174.png',
  'مقدّمات الارتعاج: العلامات التحذيرية ومراقبة الضغط': 'assets/images/article_pics/a175.png',
  'الأدوية والمتابعة الطبية لارتفاع الضغط': 'assets/images/article_pics/a176.png',
  'الراحة وإدارة التوتر مع ارتفاع الضغط': 'assets/images/article_pics/a177.png',
  'الولادة وما بعدها مع ارتفاع الضغط': 'assets/images/article_pics/a178.png',
  'التحضير الصحيح للحليب والتعقيم والنظافة': 'assets/images/article_pics/a180.png',
  'كميات الحليب وجدول الرضعات حسب العمر': 'assets/images/article_pics/a250.png',
  'تقنية الإرضاع بالزجاجة والتواصل مع طفلك': 'assets/images/article_pics/a182.png',
  'مشاكل شائعة في الرضاعة الصناعية وحلولها': 'assets/images/article_pics/a267.png',
  'التخزين والسفر والعناية اليومية والفطام': 'assets/images/articles/cat_travel.png',
  'الرضاعة المختلطة: متى ولماذا تختارينها': 'assets/images/article_pics/a188.png',
  'الحفاظ على إدرار الحليب مع الرضاعة المختلطة': 'assets/images/article_pics/a186.png',
  'شفط الحليب وتخزينه للأم في الرضاعة المختلطة': 'assets/images/article_pics/a191.png',
  'مشاكل شائعة في الرضاعة المختلطة وحلولها': 'assets/images/article_pics/a189.png',
  'العودة للعمل والرضاعة المختلطة': 'assets/images/article_pics/a193.png',
  'الدورة غير المنتظمة: ما هي وأسبابها': 'assets/images/article_pics/a356.png',
  'متى يكون عدم الانتظام طبيعيًا ومتى يستدعي الانتباه': 'assets/images/article_pics/a192.png',
  'تتبّع الدورة وتحسين دقّة التوقّعات': 'assets/images/article_pics/a003.png',
  'نمط الحياة لتنظيم الدورة': 'assets/images/article_pics/a194.png',
  'الدورة غير المنتظمة والحمل والتبويض': 'assets/images/article_pics/a195.png',
  'متى تُراجَع الطبيبة والفحوصات المحتملة': 'assets/images/article_pics/a197.png',
  'غثيان الحمل: لماذا يحدث ومتى يبدأ وينتهي': 'assets/images/article_pics/a231.png',
  'أطعمة ومشروبات تخفّف غثيان الحمل': 'assets/images/article_pics/a198.png',
  'عادات يومية للتعامل مع غثيان الحمل': 'assets/images/article_pics/a199.png',
  'القيء الحملي المفرط: متى يصبح الغثيان خطيرًا': 'assets/images/article_pics/a200.png',
  'كيف تحصلين على غذائك رغم الغثيان': 'assets/images/article_pics/a201.png',
  'الدعم النفسي أثناء غثيان الحمل': 'assets/images/article_pics/a202.png',
  'حملك الأول: مرحبًا بمرحلة جديدة': 'assets/images/article_pics/a203.png',
  'متابعة الحمل: المواعيد والفحوصات الأساسية': 'assets/images/article_pics/a173.png',
  'تغذية الحامل الأولى: أساسيات سهلة': 'assets/images/article_pics/a205.png',
  'أعراض الحمل الشائعة وكيف تتعاملين معها': 'assets/images/article_pics/a206.png',
  'الاستعداد للولادة في حملك الأول': 'assets/images/article_pics/a207.png',
  'العناية بنفسك جسديًا ونفسيًا في حملك الأول': 'assets/images/article_pics/a229.png',
  'مرحبًا بطفلك الأول: الأيام الأولى في المنزل': 'assets/images/article_pics/a209.png',
  'رضاعة مولودك الأول: بداية صحيحة': 'assets/images/article_pics/a211.png',
  'العناية اليومية بالمولود: الحفّاض والاستحمام والعناية بالجلد': 'assets/images/articles/cat_baby_bath.png',
  'متى تقلقين ومتى تطمئنّين: إشارات صحة المولود': 'assets/images/article_pics/a213.png',
  'صحتك النفسية كأم جديدة': 'assets/images/article_pics/a214.png',
  'تكيّس المبايض: ما هو وأعراضه وتشخيصه': 'assets/images/article_pics/a221.png',
  'تكيّس المبايض والخصوبة: كيف يؤثّر وكيف تحملين': 'assets/images/article_pics/a216.png',
  'نمط الحياة والتغذية لتكيّس المبايض': 'assets/images/article_pics/a217.png',
  'العلاج الطبي وتنشيط الإباضة لتكيّس المبايض': 'assets/images/article_pics/a218.png',
  'الأعراض المصاحبة لتكيّس المبايض والعناية بها': 'assets/images/article_pics/a295.png',
  'تكيّس المبايض على المدى الطويل والوقاية': 'assets/images/article_pics/a220.png',
  'الغدة الدرقية: دورها وأنواع اضطراباتها': 'assets/images/article_pics/a227.png',
  'خمول الغدة الدرقية والخصوبة والحمل': 'assets/images/article_pics/a222.png',
  'فرط نشاط الغدة الدرقية والخصوبة والحمل': 'assets/images/article_pics/a223.png',
  'تشخيص اضطرابات الغدة الدرقية والفحوصات': 'assets/images/article_pics/a224.png',
  'علاج الغدة الدرقية والمتابعة في الحمل والرضاعة': 'assets/images/article_pics/a225.png',
  'نمط الحياة والتعايش مع اضطراب الغدة الدرقية': 'assets/images/article_pics/a226.png',
  'طفلكِ الخديج: ماذا تعني الولادة المبكرة': 'assets/images/article_pics/a258.png',
  'تغذية الطفل الخديج والرضاعة': 'assets/images/article_pics/a233.png',
  'العمر المصحّح ومتابعة نموّ طفلكِ الخديج': 'assets/images/article_pics/a230.png',
  'العناية بالطفل الخديج في المنزل بعد الخروج': 'assets/images/articles/cat_delivery_recovery.png',
  'دعمكِ النفسي كأمّ لطفل خديج': 'assets/images/article_pics/a298.png',
  'الولادة القيصرية: ما هي ومتى تكون الخيار الأنسب': 'assets/images/article_pics/a265.png',
  'الفرق بين القيصرية المخطّطة والطارئة وما تتوقّعينه': 'assets/images/article_pics/a234.png',
  'التحضير للقيصرية المخطّطة: الأيام التي تسبق العملية': 'assets/images/article_pics/a238.png',
  'يوم العملية: التخدير والخطوات وماذا يحدث': 'assets/images/article_pics/a237.png',
  'أسئلة مهمّة تطرحينها على طبيبتك قبل القيصرية': 'assets/images/article_pics/a236.png',
  'القيصرية ولادة كاملة: طمأنينة نفسية قبل الموعد': 'assets/images/article_pics/a235.png',
  'التعافي في الأيام الأولى بعد الولادة القيصرية': 'assets/images/article_pics/a239.png',
  'العناية بجرح القيصرية والوقاية من الالتهاب': 'assets/images/article_pics/a240.png',
  'إدارة الألم والحركة والنهوض الآمن بعد القيصرية': 'assets/images/article_pics/a242.png',
  'الرضاعة الطبيعية بعد القيصرية: أوضاع مريحة وحلول': 'assets/images/article_pics/a241.png',
  'علامات الخطر بعد القيصرية التي تستدعي الطبيب فورًا': 'assets/images/article_pics/a243.png',
  'الحمل القادم بعد القيصرية: المباعدة والولادة الطبيعية لاحقًا': 'assets/images/article_pics/a244.png',
  'راحتك وإدارة أعراضك اليومية في حمل التوأم': 'assets/images/article_pics/a284.png',
  'مستقبل صحتك بعد سكري الحمل والوقاية المستمرة': 'assets/images/article_pics/a282.png',
  'تنظيف وتعقيم زجاجات الرضاعة بالأساليب العلمية': 'assets/images/article_pics/a249.png',
  'التغيرات في جسمك أسبوعياً': 'assets/images/article_pics/a287.png',
  'مراحل نمو الجنين': 'assets/images/article_pics/a288.png',
  'متى تزورين الطبيبة؟': 'assets/images/articles/cat_women_health.png',
  'الأطعمة المفيدة للحامل': 'assets/images/articles/cat_nutrition.png',
  'أطعمة يجب تجنبها': 'assets/images/article_pics/a253.png',
  'المشروبات الصحية للحامل': 'assets/images/article_pics/a248.png',
  'الفيتامينات الضرورية': 'assets/images/article_pics/a256.png',
  'آلام الظهر وكيفية التخفيف': 'assets/images/article_pics/a277.png',
  'الغثيان الصباحي': 'assets/images/article_pics/a165.png',
  'تورم القدمين والساقين': 'assets/images/articles/cat_exercise.png',
  'المشي أثناء الحمل': 'assets/images/articles/cat_walking.png',
  'يوغا الحوامل': 'assets/images/article_pics/a264.png',
  'السباحة للحامل': 'assets/images/article_pics/a262.png',
  'تمارين كيجل المهمة': 'assets/images/articles/cat_postpartum_fitness.png',
  'الرضاعة الطبيعية: البداية': 'assets/images/articles/cat_breastfeeding.png',
  'تحضير حقيبة المولود': 'assets/images/articles/cat_birth_prep.png',
  'الرضاعة بالزجاجة': 'assets/images/articles/cat_bottle_feeding.png',
  'وضعيات النوم الآمنة': 'assets/images/articles/cat_sleep_pregnancy.png',
  'التغلب على الأرق': 'assets/images/article_pics/a269.png',
  'التعب والإرهاق': 'assets/images/article_pics/a270.png',
  'التقلبات المزاجية': 'assets/images/article_pics/a273.png',
  'القلق من الولادة': 'assets/images/article_pics/a261.png',
  'اكتئاب ما بعد الولادة': 'assets/images/article_pics/a245.png',
  'متى تخبرين عملك؟': 'assets/images/article_pics/a272.png',
  'الراحة في المكتب': 'assets/images/article_pics/a204.png',
  'إجازة الأمومة والتحضير': 'assets/images/articles/cat_husband_support.png',
  'دور الأب أثناء الحمل': 'assets/images/article_pics/a251.png',
  'العلاقة الزوجية والحمل': 'assets/images/article_pics/a279.png',
  'فحص السونار التفصيلي': 'assets/images/article_pics/a281.png',
  'فحص سكر الحمل': 'assets/images/article_pics/a247.png',
  'العناية بالبشرة': 'assets/images/articles/cat_skincare.png',
  'العناية بالشعر': 'assets/images/article_pics/a283.png',
  'الملابس المريحة': 'assets/images/articles/cat_fashion.png',
  'ما هو الوحم علمياً وأسبابه الحقيقية؟': 'assets/images/article_pics/a285.png',
  'اشتهاء الحامض والمالح والحلو: الحقائق والخرافات': 'assets/images/article_pics/a190.png',
  'وحم المواد غير الغذائية (متلازمة البيكا) ومخاطرها': 'assets/images/articles/cat_meal_prep.png',
  'التعامل مع كره الأطعمة والنفور الغذائي أثناء الحمل': 'assets/images/article_pics/a321.png',
  'الوحم والغثيان الصباحي: كيف تؤثر شهيتك على صحتك؟': 'assets/images/article_pics/a289.png',
  'الوحم النفسي والعاطفي: هل هو مجرد دلع؟': 'assets/images/article_pics/a290.png',
  'لغة الجسد: هل يعكس الوحم نقصاً في الفيتامينات؟': 'assets/images/article_pics/a259.png',
  'دليلك للبدائل الصحية لأطعمة الوحم الضارة': 'assets/images/article_pics/a292.png',
  'وحم الروائح أثناء الحمل: الأسباب وطرق التغلب عليه': 'assets/images/article_pics/a254.png',
  'متى ينتهي الوحم؟ الجدول الزمني لشهية الحامل ونفورها': 'assets/images/articles/cat_mental_health.png',
  'الدليل النفسي لاختيار اسم الطفل وأثره على شخصيته': 'assets/images/articles/cat_spiritual.png',
  'أفكار لاختيار أسماء توائم متناسقة وعصرية': 'assets/images/article_pics/a297.png',
  'أثر الاسم على الرزق والبركة والتفاؤل': 'assets/images/article_pics/a184.png',
  'الأسماء المكروهة والمحرمة في الإسلام': 'assets/images/article_pics/a299.png',
  'التسمية في اليوم السابع وسنن الولادة المباركة': 'assets/images/article_pics/a301.png',
  'حكم التسمية بأسماء الملائكة وسور القرآن': 'assets/images/article_pics/a302.png',
  'كيف تتجنب تنمر الأقران بسبب اسم طفلك؟': 'assets/images/article_pics/a303.png',
  'خطوات عملية للاتفاق بين الزوجين على الاسم': 'assets/images/article_pics/a304.png',
  'أسرار وتناغم الاسم مع اسم الأب والعائلة': 'assets/images/article_pics/a305.png',
  'أثر الاسم على الرزق والبركة: نظرة شرعية وتفاؤل': 'assets/images/article_pics/a307.png',
  'فهم دورتك الشهرية': 'assets/images/articles/cat_cycle.png',
  'تخفيف آلام الدورة': 'assets/images/articles/cat_postpartum_support.png',
  'الدورة غير المنتظمة: الأسباب والعلاج': 'assets/images/article_pics/a310.png',
  'الدورة الشهرية والنظافة الشخصية': 'assets/images/article_pics/a311.png',
  'حساب أيام التبويض': 'assets/images/article_pics/a313.png',
  'علامات التبويض الطبيعية': 'assets/images/article_pics/x001.png',
  'نصائح لتعزيز الخصوبة طبيعياً': 'assets/images/article_pics/a280.png',
  'متلازمة تكيس المبايض': 'assets/images/article_pics/a228.png',
  'أطعمة تخفف أعراض الدورة': 'assets/images/article_pics/a317.png',
  'المكملات الغذائية المفيدة للدورة': 'assets/images/article_pics/a274.png',
  'الترطيب وأهمية الماء أثناء الدورة': 'assets/images/article_pics/a312.png',
  'تقلبات المزاج أثناء الدورة': 'assets/images/article_pics/a215.png',
  'النوم والراحة أثناء الدورة': 'assets/images/article_pics/a309.png',
  'العناية بالحبل السري للمولود': 'assets/images/article_pics/a322.png',
  'نوم المولود: أنماط وتوجيهات آمنة': 'assets/images/article_pics/a342.png',
  'اليرقان عند حديثي الولادة': 'assets/images/article_pics/a324.png',
  'المغص عند الرضع: الأسباب والتهدئة': 'assets/images/article_pics/a326.png',
  'التسنين: الأعراض والتخفيف': 'assets/images/articles/cat_teething.png',
  'الحبو والزحف: تشجيع الحركة الأولى': 'assets/images/article_pics/a332.png',
  'قلق الانفصال عند الرضيع': 'assets/images/article_pics/a334.png',
  'تأمين المنزل للطفل المتحرك': 'assets/images/article_pics/a335.png',
  'تطور التواصل واللغة من 6 إلى 9 أشهر': 'assets/images/article_pics/a336.png',
  'الخطوات الأولى: تشجيع المشي بأمان': 'assets/images/articles/cat_toddler.png',
  'الكلمات الأولى وتطور اللغة': 'assets/images/article_pics/a338.png',
  'نوبات الغضب والتعامل مع مشاعر الطفل': 'assets/images/article_pics/a343.png',
  'الاستعداد للتدريب على الحمام': 'assets/images/article_pics/a347.png',
  'المهارات الاجتماعية واللعب مع الآخرين': 'assets/images/articles/cat_family.png',
  'الحمى عند الرضع: متى تقلقين': 'assets/images/article_pics/a348.png',
  'جدول التطعيمات الأساسية للطفل': 'assets/images/articles/cat_vaccination.png',
  'العناية ببشرة الطفل الحساسة': 'assets/images/articles/cat_newborn.png',
  'الأمراض الشائعة عند الأطفال وعلاجها': 'assets/images/article_pics/a349.png',
  'سلامة الطفل والإسعافات الأولية المنزلية': 'assets/images/article_pics/a350.png',
  'فوائد الأسماك للحامل': 'assets/images/article_pics/a351.png',
  'تغذية الشهور الأخيرة': 'assets/images/article_pics/x014.png',
  'التعامل مع الأرق أثناء الحمل': 'assets/images/article_pics/a255.png',
  'تجهيز غرفة المولود': 'assets/images/article_pics/y005.png',
  'الرضاعة الطبيعية: البداية الصحيحة': 'assets/images/article_pics/a355.png',
  'متى تتصلين بالطبيبة فوراً': 'assets/images/articles/cat_prenatal_checkup.png',
  'أصغر توائم رباعية خدّج في التاريخ ينجون': 'assets/images/article_pics/a360.png',
  'توأمان يولدان في سنتين مختلفتين بفارق 15 دقيقة': 'assets/images/article_pics/a366.png',
  'طفل يولد بسنّين كاملتين يثير دهشة الأطباء': 'assets/images/article_pics/a368.png',
  'أم تكتشف حملها قبل الولادة بساعات فقط': 'assets/images/article_pics/a369.png',
  'توأمان متطابقان يولدان بلونَي بشرة مختلفين تماماً': 'assets/images/article_pics/a370.png',
  'أصغر طفل خديج في العالم يحتفل بعيده الخامس': 'assets/images/article_pics/a371.png',
  'دراسة: أطفال يتعرفون على أصوات أمهاتهم من الرحم': 'assets/images/article_pics/a373.png',
  'طفلة تولد بخصلة شعر بيضاء وراثية نادرة': 'assets/images/article_pics/a374.png',
  'أب يحضر ولادة ابنته عبر الفيديو من الفضاء': 'assets/images/article_pics/a376.png',
  'اكتشاف أن حليب الأم يتغير تركيبه حسب جنس المولود': 'assets/images/article_pics/a377.png',
  'مستشفى يعزف الموسيقى للأجنة ويحسن نموهم': 'assets/images/article_pics/a378.png',
  'أم تنجب طفلتها في سيارة إسعاف على الطريق السريع': 'assets/images/article_pics/a379.png',
  'ممرضة تكتشف أنها أنجبت التوأم الذي تعتني به في الحضانة': 'assets/images/article_pics/a381.png',
  'دراسة: الأطفال الذين يسمعون لغتين يتطور دماغهم أسرع': 'assets/images/article_pics/a382.png',
  'توأمان ملتصقان يُفصلان بنجاح بعد عملية 36 ساعة': 'assets/images/article_pics/a383.png',
  'أصغر أم تتبرع بحليبها لإنقاذ مائة طفل خديج': 'assets/images/article_pics/a384.png',
  'طفل يولد في طائرة على ارتفاع 10 آلاف متر': 'assets/images/article_pics/a385.png',
  'علماء يطورون حفاضاً ذكياً ينبه الوالدين صحياً': 'assets/images/article_pics/a386.png',
  'سيدة مصرية تنجب بعد 25 سنة من العقم': 'assets/images/article_pics/a387.png',
  'مولود يبتسم ابتسامة عريضة لحظة ولادته': 'assets/images/article_pics/a388.png',
  'مدينة يابانية تقدم مكافأة مليون ين لكل مولود جديد': 'assets/images/article_pics/a389.png',
};
