// GENERATED — خريطة عنوان المقال → صورته الفريدة
// DO NOT EDIT BY HAND.
// 56 unique hero images for articles: a151–a182, a366–a389
// Remaining articles (a183–a365) fall back to category images.


const Map<String, String> kArticleImageMap = {
  'أذكار الحامل اليومية': 'assets/images/article_pics/a151.png',
  'أدعية الولادة الميسّرة': 'assets/images/article_pics/a152.png',
  'أحكام الصلاة للحامل والنفساء': 'assets/images/article_pics/a153.png',
  'الصيام للحامل والمرضع': 'assets/images/article_pics/a154.png',
  'بركة الرضاعة الطبيعية في الإسلام': 'assets/images/article_pics/a155.png',
  'تربية الأطفال على المحبّة في الإسلام': 'assets/images/article_pics/a156.png',
  'تعليم الطفل الوضوء والصلاة': 'assets/images/article_pics/a157.png',
  'أسماء أولاد وبنات إسلامية بمعانيها': 'assets/images/article_pics/a158.png',
  'أذكار حفظ الأطفال من العين والحسد': 'assets/images/article_pics/a159.png',
  'حقّ الأم على ابنها في الإسلام': 'assets/images/article_pics/a160.png',
  'الحمل بتوأم: نظرة شاملة وأنواعه': 'assets/images/article_pics/a161.png',
  'تغذية الحامل بتوأم': 'assets/images/article_pics/a162.png',
  'متابعة حمل التوأم ومخاطره المحتملة': 'assets/images/article_pics/a163.png',
  'رضاعة التوأم والعناية بهما في الأشهر الأولى': 'assets/images/article_pics/a164.png',
  'سيكولوجية تربية التوائم والترابط الفردي': 'assets/images/article_pics/a165.png',
  'الاستعداد لولادة التوأم': 'assets/images/article_pics/a166.png',
  'سكري الحمل: ما هو ولماذا يحدث': 'assets/images/article_pics/a167.png',
  'النظام الغذائي لسكري الحمل': 'assets/images/article_pics/a168.png',
  'مراقبة سكر الدم في المنزل': 'assets/images/article_pics/a169.png',
  'النشاط البدني وسكري الحمل': 'assets/images/article_pics/a170.png',
  'متى تحتاجين دواءً أو إنسولين والمتابعة': 'assets/images/article_pics/a171.png',
  'سكري الحمل بعد الولادة والوقاية مستقبلًا': 'assets/images/article_pics/a172.png',
  'ارتفاع ضغط الدم في الحمل: أنواعه وأسبابه': 'assets/images/article_pics/a173.png',
  'التغذية ونمط الحياة لخفض الضغط في الحمل': 'assets/images/article_pics/a174.png',
  'مقدّمات الارتعاج: العلامات التحذيرية ومراقبة الضغط': 'assets/images/article_pics/a175.png',
  'الأدوية والمتابعة الطبية لارتفاع الضغط': 'assets/images/article_pics/a176.png',
  'الراحة وإدارة التوتر مع ارتفاع الضغط': 'assets/images/article_pics/a177.png',
  'الولادة وما بعدها مع ارتفاع الضغط': 'assets/images/article_pics/a178.png',
  'الرضاعة الصناعية: متى ولماذا وكيف تختارين الحليب': 'assets/images/article_pics/a179.png',
  'التحضير الصحيح للحليب والتعقيم والنظافة': 'assets/images/article_pics/a180.png',
  'كميات الحليب وجدول الرضعات حسب العمر': 'assets/images/article_pics/a181.png',
  'تقنية الإرضاع بالزجاجة والتواصل مع طفلك': 'assets/images/article_pics/a182.png',
  'توأمان يولدان في سنتين مختلفتين بفارق 15 دقيقة': 'assets/images/article_pics/a366.png',
  'سيدة أفريقية تنجب 10 توائم في ولادة واحدة': 'assets/images/article_pics/a367.png',
  'طفل يولد بسنّين كاملتين يثير دهشة الأطباء': 'assets/images/article_pics/a368.png',
  'أم تكتشف حملها قبل الولادة بساعات فقط': 'assets/images/article_pics/a369.png',
  'توأمان متطابقان يولدان بلونَي بشرة مختلفين تماماً': 'assets/images/article_pics/a370.png',
  'أصغر طفل خديج في العالم يحتفل بعيده الخامس': 'assets/images/article_pics/a371.png',
  'امرأة تنجب طفلاً أثناء غيبوبة استمرت 3 أشهر': 'assets/images/article_pics/a372.png',
  'دراسة: أطفال يتعرفون على أصوات أمهاتهم من الرحم': 'assets/images/article_pics/a373.png',
  'طفلة تولد بخصلة شعر بيضاء وراثية نادرة': 'assets/images/article_pics/a374.png',
  'دراسة: الرضاعة الطبيعية تحمي من 800 ألف وفاة سنوياً': 'assets/images/article_pics/a375.png',
  'أب يحضر ولادة ابنته عبر الفيديو من الفضاء': 'assets/images/article_pics/a376.png',
  'اكتشاف أن حليب الأم يتغير تركيبه حسب جنس المولود': 'assets/images/article_pics/a377.png',
  'مستشفى يعزف الموسيقى للأجنة ويحسن نموهم': 'assets/images/article_pics/a378.png',
  'أم تنجب طفلتها في سيارة إسعاف على الطريق السريع': 'assets/images/article_pics/a379.png',
  'تقنية جديدة تتيح للأجنة التنفس خارج الرحم': 'assets/images/article_pics/a380.png',
  'ممرضة تكتشف أنها أنجبت التوأم الذي تعتني به في الحضانة': 'assets/images/article_pics/a381.png',
  'دراسة: الأطفال الذين يسمعون لغتين يتطور دماغهم أسرع': 'assets/images/article_pics/a382.png',
  'توأمان ملتصقان يُفصلان بنجاح بعد عملية 36 ساعة': 'assets/images/article_pics/a383.png',
  'أصغر أم تتبرع بحليبها لإنقاذ مائة طفل خديج': 'assets/images/article_pics/a384.png',
  'طفل يولد في طائرة على ارتفاع 10 آلاف متر': 'assets/images/article_pics/a385.png',
  'علماء يطورون حفاضاً ذكياً ينبه الوالدين صحياً': 'assets/images/article_pics/a386.png',
  'سيدة مصرية تنجب بعد 25 سنة من العقم': 'assets/images/article_pics/a387.png',
  'مولود يبتسم ابتسامة عريضة لحظة ولادته': 'assets/images/article_pics/a388.png',
  'مدينة يابانية تقدم مكافأة مليون ين لكل مولود جديد': 'assets/images/article_pics/a389.png',
};